/**
 * Types for public/data/population-security.json
 * Generated by scripts/population-pipeline/generate.py
 *
 * Re-run the pipeline any time to refresh:
 *   python scripts/population-pipeline/generate.py
 */

export interface DilutionPoint {
  year: number
  per_capita_pkr: number
}

export interface ProjectionPoint {
  year: number
  pop_m: number
}

export interface ProvinceProjections {
  high:   ProjectionPoint[]
  medium: ProjectionPoint[]
  low:    ProjectionPoint[]
}

export interface SecurityLevel {
  score: number     // 0–100
  level: 'Low' | 'Medium' | 'High' | 'Critical'
}

export interface ProvinceSecurityData {
  province:               string
  pop_2017_m:             number
  pop_2023_m:             number
  pop_2030_m:             number
  pop_2050_m:             number
  growth_rate:            number   // % p.a.
  fertility_rate:         number   // births per woman
  youth_15_29_pct:        number   // % of total pop
  youth_of_working_pct:   number   // % of working-age pop
  literacy_pct:           number
  urban_pct:              number
  dependency_ratio:       number   // dependents per 100 working-age
  instability_index:      number   // 0–100 (PIPS proxy)
  security:               SecurityLevel
  psdp_alloc_bn:          number   // PKR billion FY2024-25
  psdp_per_capita_pkr:    number
  dilution_curve:         DilutionPoint[]
  projections:            ProvinceProjections
}

export interface TrendPoint {
  year:  number
  value: number
}

export interface NationalTrends {
  pop_growth_pct:       TrendPoint[]
  fertility_rate:       TrendPoint[]
  dependency_ratio:     TrendPoint[]
  working_age_pct:      TrendPoint[]
  youth_unemployment_pct: TrendPoint[]
  total_population:     TrendPoint[]
  pop_under14_pct:      TrendPoint[]
  pop_over65_pct:       TrendPoint[]
}

export interface SecurityScatterPoint {
  province:            string
  youth_bulge_pct:     number
  instability_index:   number
  security_score:      number
  security_level:      SecurityLevel['level']
  growth_rate:         number
  psdp_per_capita_pkr: number
}

export interface PopulationSecurityData {
  meta: {
    generated_at: string
    fiscal_year:  string
    census_year:  number
    sources:      string[]
  }
  national_summary: {
    total_pop_2023_m:          number
    pakistan_2050_medium_m:    number
    national_growth_rate_2023: number
    national_fertility_2023:   number
    national_youth_unemp_2023: number
    national_dependency_2023:  number
  }
  national_trends:   NationalTrends
  provinces:         ProvinceSecurityData[]
  security_scatter:  SecurityScatterPoint[]
}

/** Import statically — works in both Server and Client components */
// eslint-disable-next-line @typescript-eslint/no-require-imports
export const populationSecurityData: PopulationSecurityData =
  require('../../public/data/population-security.json') as PopulationSecurityData

/** Lookup a single province's data */
export function getProvinceSecurityData(province: string): ProvinceSecurityData | undefined {
  return populationSecurityData.provinces.find(p => p.province === province)
}

/** Colour for a security level */
export const SECURITY_LEVEL_STYLE: Record<SecurityLevel['level'], { bg: string; color: string; border: string }> = {
  Low:      { bg: '#f0fdf4', color: '#16a34a', border: '#86efac' },
  Medium:   { bg: '#fff7ed', color: '#ea580c', border: '#fdba74' },
  High:     { bg: '#fef2f2', color: '#dc2626', border: '#fca5a5' },
  Critical: { bg: '#450a0a', color: '#fca5a5', border: '#991b1b' },
}
