-- ── funders_master table ──────────────────────────────────────────────────────
-- Canonical registry of all active funders in Pakistan's development landscape.
-- Replaces the hardcoded FUNDERS array in funder-coverage.tsx.

CREATE TABLE IF NOT EXISTS public.funders_master (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name             text NOT NULL UNIQUE,
  type             text NOT NULL,           -- Bilateral | Multilateral | UN | Philanthropy | Climate | Pakistan
  status           text NOT NULL DEFAULT 'active',  -- active | partial_freeze | limited | exited
  trend            text NOT NULL DEFAULT 'stable',  -- growing | stable | shrinking
  sectors          text[] NOT NULL DEFAULT '{}',
  budget_label     text,
  signal           text,
  procurement_url  text,
  country_url      text,
  country          text,
  confidence_score integer NOT NULL DEFAULT 80,   -- 0-100
  last_verified    date,
  portfolio_end_date date,                        -- when portfolio closes / last known project end
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.funders_master ENABLE ROW LEVEL SECURITY;

CREATE POLICY "funders_master_select" ON public.funders_master
  FOR SELECT USING (true);

CREATE POLICY "funders_master_admin_all" ON public.funders_master
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid() AND role = 'admin'
    )
  );

-- ── Seed data ─────────────────────────────────────────────────────────────────

INSERT INTO public.funders_master
  (name, type, status, trend, sectors, budget_label, signal, procurement_url, country_url, country, confidence_score, last_verified)
VALUES
  -- Bilateral
  ('FCDO (UK)',         'Bilateral', 'active',         'stable',   ARRAY['Education','Governance','Health','Gender'],                      '$200M+/yr',     'CDPS Phase II design starting. UK spending review may constrain envelope. Girls education Balochistan pilot under discussion.',                                       'https://www.gov.uk/contracts-finder',                                              'https://www.gov.uk/world/pakistan',                    'UK',          85, '2026-03-01'),
  ('GIZ (Germany)',     'Bilateral', 'active',         'growing',  ARRAY['Energy','Governance','Rural Development','Agriculture'],          '€60M+/yr',      'PGCEP Phase II (~€45M) biggest bilateral opportunity in 2026. German BMZ Pakistan budget growing.',                                                                      'https://www.giz.de/en/medien/ausschreibungen.html',                                'https://www.giz.de/en/worldwide/322.html',             'Germany',     90, '2026-03-01'),
  ('USAID',             'Bilateral', 'partial_freeze', 'shrinking',ARRAY['Health','Education','Governance','Agriculture'],                  '$200M+/yr',     'Stop-work orders in effect on multiple programmes. Portfolio review ongoing. Substitution signals emerging for EU, GIZ, FCDO.',                                     'https://www.usaid.gov/pakistan',                                                   'https://www.usaid.gov/pakistan',                       'USA',         75, '2026-03-01'),
  ('JICA (Japan)',      'Bilateral', 'active',         'stable',   ARRAY['Infrastructure','Water/Sanitation','Agriculture','Transport'],    '$150M+/yr',     'Strong infrastructure pipeline. Karachi water and transport focus. New rural development window under preparation.',                                                  'https://www.jica.go.jp/pakistan/',                                                 'https://www.jica.go.jp/pakistan/',                     'Japan',       85, '2026-03-01'),
  ('KfW (Germany)',     'Bilateral', 'active',         'stable',   ARRAY['Water/Sanitation','Energy','Financial Inclusion'],               '€40M+/yr',      'Financial sector and WASH focus. Works closely with GIZ on energy transition.',                                                                                       'https://www.kfw-entwicklungsbank.de',                                              '',                                                     'Germany',     80, '2026-03-01'),
  ('AFD (France)',      'Bilateral', 'active',         'stable',   ARRAY['Climate','Agriculture','Urban'],                                 '€30M+/yr',      'Climate and urban development focus. Exploring agri-food value chains.',                                                                                              'https://www.afd.fr',                                                               '',                                                     'France',      80, '2026-03-01'),
  ('EU Delegation Pakistan','Bilateral','active',      'growing',  ARRAY['Governance','Rule of Law','Trade','Climate'],                    '€150M+/yr',     'Multi-Annual Indicative Programme 2027-2030 finalisation in progress. Pre-positioning now is strategic.',                                                             'https://ec.europa.eu/info/funding-tenders/opportunities/portal/',                  'https://www.eeas.europa.eu/delegations/pakistan',      'EU',          90, '2026-03-01'),
  ('SDC (Switzerland)', 'Bilateral', 'active',         'stable',   ARRAY['Governance','WASH','Rural Development','Education'],             'CHF 50M+/yr',   'Rural development and local governance strong focus. Deepening Balochistan and GB engagement.',                                                                    'https://www.eda.admin.ch/sdc',                                                     '',                                                     'Switzerland', 80, '2026-03-01'),
  ('KOICA (South Korea)','Bilateral','active',         'stable',   ARRAY['Health','Education','ICT','Agriculture'],                        '$20M+/yr',      'Health infrastructure and ICT emerging. Bilateral relations strengthening.',                                                                                          'https://www.koica.go.kr',                                                          '',                                                     'South Korea', 75, '2026-03-01'),
  ('TIKA (Turkey)',     'Bilateral', 'active',         'stable',   ARRAY['Education','Humanitarian','Health'],                             '$10M+/yr',      'Education and humanitarian focus. Active in AJK and Balochistan.',                                                                                                    'https://www.tika.gov.tr',                                                          '',                                                     'Turkey',      70, '2026-03-01'),
  ('USDA (US Agriculture)','Bilateral','active',       'stable',   ARRAY['Agriculture','Food Security'],                                  '$20M+/yr',      'Food security and agricultural development. McGovern-Dole programme active.',                                                                                         'https://www.fas.usda.gov',                                                         '',                                                     'USA',         75, '2026-03-01'),
  ('DFAT (Australia)',  'Bilateral', 'limited',        'stable',   ARRAY['Education','Governance'],                                       'AUD 10M+/yr',   'Limited but consistent bilateral. Girls education and governance focus.',                                                                                              'https://www.dfat.gov.au/geo/pakistan',                                             '',                                                     'Australia',   70, '2026-03-01'),
  ('Enabel (Belgium)',  'Bilateral', 'active',         'stable',   ARRAY['Health','Agriculture'],                                         '€15M+/yr',      'Health systems and agricultural development in rural areas.',                                                                                                         'https://www.enabel.be',                                                            '',                                                     'Belgium',     70, '2026-03-01'),
  ('Expertise France',  'Bilateral', 'active',         'growing',  ARRAY['Governance','Education','Health'],                              '€10M+/yr',      'Technical assistance arm of AFD. EU-funded TA often implemented through Expertise France.',                                                                           'https://www.expertisefrance.fr',                                                   '',                                                     'France',      70, '2026-03-01'),
  -- Multilateral
  ('World Bank',        'Multilateral','active',       'growing',  ARRAY['Governance','Education','Health','Infrastructure','Energy'],     '$1.2B+/yr',     'RISE Programme DLI 3 on track. FY27 pipeline includes urban resilience and secondary education. Stable country envelope.',                                           'https://projects.worldbank.org/en/projects-operations/procurement',                'https://www.worldbank.org/en/country/pakistan',        'USA',         95, '2026-03-01'),
  ('ADB',               'Multilateral','active',       'growing',  ARRAY['Energy','Transport','Agriculture','Finance'],                    '$1.5B+/yr',     'Energy transition facility under design. Punjab agriculture executing well. Q2 2026 country partnership strategy update expected.',                                    'https://www.adb.org/business/opportunities',                                       'https://www.adb.org/countries/pakistan/main',          'Philippines', 95, '2026-03-01'),
  ('IMF',               'Multilateral','active',       'stable',   ARRAY['Fiscal Reform','Monetary Policy','Financial Sector'],           'Programme-based','EFF programme ongoing. 9th review expected Q2 2026. Prior actions on FBR and energy tariff critical.',                                                             'N/A',                                                                              'https://www.imf.org/en/countries/PAK',                 'USA',         90, '2026-03-01'),
  ('Islamic Development Bank (IsDB)','Multilateral','active','growing',ARRAY['Infrastructure','Education','Health','Agriculture'],        '$300M+/yr',     'Strong pipeline in transport, education, and agriculture. IsDB-ITFC trade finance active.',                                                                          'https://www.isdb.org/what-we-do/procurement',                                      'https://www.isdb.org',                                 'Saudi Arabia',85, '2026-03-01'),
  ('AIIB',              'Multilateral','active',       'growing',  ARRAY['Infrastructure','Energy','Water'],                              '$200M+/yr',     'Infrastructure and climate focus. Co-financing with World Bank and ADB increasingly common.',                                                                          'https://www.aiib.org/en/opportunities/business/procurement/',                      '',                                                     'China',       80, '2026-03-01'),
  ('OPEC Fund',         'Multilateral','active',       'stable',   ARRAY['Infrastructure','Agriculture','Energy'],                        '$100M+/yr',     'Infrastructure loans and co-financing. Works with bilateral and multilateral partners.',                                                                               'https://opecfund.org',                                                             '',                                                     'Austria',     75, '2026-03-01'),
  ('IFAD',              'Multilateral','active',       'stable',   ARRAY['Agriculture','Rural Development','Food Security'],              '$80M+/yr',      'Rural livelihoods and smallholder agriculture focus. Strong rural ADP complementarity.',                                                                              'https://www.ifad.org/en/business-opportunities',                                   '',                                                     'Italy',       80, '2026-03-01'),
  -- UN
  ('UNDP Pakistan',     'UN',        'active',         'stable',   ARRAY['Governance','Environment','DRR','Gender'],                      '$50M+/yr',      'Governance and DRR strong. Transitional justice and rule of law expanding. SDG acceleration focus.',                                                                   'https://procurement-notices.undp.org/',                                            'https://www.undp.org/pakistan',                        'USA',         85, '2026-03-01'),
  ('UNICEF Pakistan',   'UN',        'active',         'stable',   ARRAY['Education','Health','WASH','Nutrition'],                        '$80M+/yr',      'Polio eradication, nutrition, and out-of-school children. WASH programme expanding.',                                                                                  'https://www.ungm.org',                                                             'https://www.unicef.org/pakistan',                      'USA',         85, '2026-03-01'),
  ('WHO Pakistan',      'UN',        'active',         'stable',   ARRAY['Health','Nutrition','Emergency Response'],                      '$30M+/yr',      'Health systems strengthening and disease surveillance. Climate-health nexus emerging.',                                                                                 'https://www.ungm.org',                                                             'https://www.emro.who.int/pak/',                        'Switzerland', 85, '2026-03-01'),
  ('WFP Pakistan',      'UN',        'active',         'stable',   ARRAY['Food Security','Nutrition','Humanitarian'],                     '$100M+/yr',     'Flood recovery and food assistance. Resilience livelihoods programme expanding in KP and Balochistan.',                                                               'https://www.wfp.org/procurement',                                                  'https://www.wfp.org/countries/pakistan',               'Italy',       85, '2026-03-01'),
  ('UNFPA Pakistan',    'UN',        'active',         'stable',   ARRAY['Health','Gender','Population'],                                '$20M+/yr',      'Reproductive health and population data. Gender-based violence response expanding.',                                                                                    'https://www.ungm.org',                                                             'https://pakistan.unfpa.org',                           'USA',         80, '2026-03-01'),
  ('FAO Pakistan',      'UN',        'active',         'stable',   ARRAY['Agriculture','Food Security','Climate'],                        '$30M+/yr',      'Locust response winding down. Climate-smart agriculture and water management expanding.',                                                                              'https://www.ungm.org',                                                             'https://www.fao.org/pakistan/en/',                     'Italy',       80, '2026-03-01'),
  ('ILO Pakistan',      'UN',        'active',         'stable',   ARRAY['Labour','TVET','Social Protection','Gender'],                   '$15M+/yr',      'Decent work and skills development. Worker rights in supply chains emerging donor interest.',                                                                          'https://www.ilo.org',                                                              'https://www.ilo.org/islamabad',                        'Switzerland', 80, '2026-03-01'),
  ('UN Women Pakistan', 'UN',        'active',         'growing',  ARRAY['Gender','Governance','Economic Empowerment'],                   '$15M+/yr',      'Women economic empowerment and political participation. Increasing bilateral co-funding.',                                                                              'https://www.ungm.org',                                                             'https://www.unwomen.org/en/where-we-are/asia-and-the-pacific/pakistan', 'USA', 80, '2026-03-01'),
  ('UNHCR Pakistan',    'UN',        'active',         'stable',   ARRAY['Humanitarian','Rule of Law','Education'],                       '$100M+/yr',     'Afghan refugee response dominant. Repatriation support and host community integration expanding.',                                                                     'https://www.unhcr.org/procurementnotices.html',                                    'https://www.unhcr.org/pk/',                            'Switzerland', 85, '2026-03-01'),
  ('UNOPS',             'UN',        'active',         'growing',  ARRAY['Infrastructure','Procurement','Humanitarian'],                  '$50M+/yr',      'Flood recovery infrastructure delivery. Procurement services for UN and bilateral donors.',                                                                            'https://www.ungm.org',                                                             '',                                                     'Denmark',     80, '2026-03-01'),
  -- Philanthropy / Climate
  ('Gates Foundation',       'Philanthropy','active',  'stable',   ARRAY['Health','Nutrition','Agriculture','Financial Inclusion'],       '$100M+/yr',     'Polio eradication, family planning, and smallholder agriculture. Digital financial inclusion growing.',                                                                'https://www.gatesfoundation.org',                                                  '',                                                     'USA',         85, '2026-03-01'),
  ('Aga Khan Development Network','Philanthropy','active','stable',ARRAY['Education','Health','Rural Development','Financial Inclusion'], '$100M+/yr',     'Massive Pakistan footprint across KP, GB, AJK. AKDN entities include AKF, AKHS, AKDN, FOCUS, AKRSP.',                                                                 'https://www.akdn.org',                                                             '',                                                     'Switzerland', 90, '2026-03-01'),
  ('Green Climate Fund (GCF)','Climate','active',      'growing',  ARRAY['Climate','Water','Agriculture','Energy'],                       '$200M+',        'Pakistan Loss & Damage fund access ongoing. National Adaptation Plan funding cycle expected 2026.',                                                                     'https://www.greenclimate.fund/tenders',                                            '',                                                     'South Korea', 80, '2026-03-01'),
  ('Adaptation Fund',        'Climate','active',       'growing',  ARRAY['Climate','Agriculture','DRR'],                                 '$30M+',         'Direct access through NDMA and ERRA. Climate adaptation in flood-prone districts.',                                                                                    'https://www.adaptation-fund.org',                                                  '',                                                     'Germany',     75, '2026-03-01'),
  ('Global Fund',            'Philanthropy','active',  'stable',   ARRAY['Health'],                                                      '$200M+/cycle',  'HIV, TB, Malaria 3-year grants. Sub-recipient market strong for health implementers.',                                                                                  'https://www.theglobalfund.org',                                                    '',                                                     'Switzerland', 85, '2026-03-01'),
  ('Gavi',                   'Philanthropy','active',  'stable',   ARRAY['Health','Nutrition'],                                          '$100M+/cycle',  'Immunization systems strengthening. Cold chain and EPI delivery focus.',                                                                                               'https://www.gavi.org',                                                             '',                                                     'Switzerland', 85, '2026-03-01'),
  -- Pakistan
  ('PPAF',                   'Pakistan','active',      'stable',   ARRAY['Financial Inclusion','Rural Development','Gender'],            'PKR billion-scale','Pakistan Poverty Alleviation Fund. Works through partner organizations. Social protection nexus.',                                                                'https://www.ppaf.org.pk',                                                          '',                                                     'Pakistan',    85, '2026-03-01'),
  ('Karandaaz',              'Pakistan','active',      'growing',  ARRAY['Financial Inclusion','SME','Digital'],                         'PKR billion-scale','UKAID and Gates-backed. Digital finance, SME lending, and agricultural finance strong.',                                                                           'https://www.karandaaz.com.pk',                                                     '',                                                     'Pakistan',    85, '2026-03-01')
ON CONFLICT (name) DO UPDATE SET
  status        = EXCLUDED.status,
  trend         = EXCLUDED.trend,
  sectors       = EXCLUDED.sectors,
  budget_label  = EXCLUDED.budget_label,
  signal        = EXCLUDED.signal,
  last_verified = EXCLUDED.last_verified,
  updated_at    = now();

GRANT SELECT ON public.funders_master TO authenticated;
GRANT SELECT ON public.funders_master TO anon;
