-- ================================================================
-- Migration 0012: Federal PSDP 2024-25 & Provincial ADP Seed Data
-- Seeds 85 schemes into public.psdp_schemes covering federal PSDP
-- (45 schemes across Water, Transport, Energy, Health, Education,
-- Agriculture, Social Protection, Digital/Governance sectors) and
-- Provincial ADPs for Punjab, Sindh, KP, and Balochistan (40 schemes).
-- Author: Syed Ali Shehryar
-- ================================================================

INSERT INTO public.psdp_schemes (
  scheme_id,
  title,
  ministry,
  executing_agency,
  province,
  district,
  sector,
  sub_sector,
  source,
  fiscal_year,
  allocation_bn,
  released_bn,
  utilized_bn,
  execution_pct,
  throwforward_bn,
  total_approved_cost_bn,
  implementation_stage,
  risk_level,
  is_slow_moving,
  is_time_overrun,
  is_revised,
  warning_signals,
  is_donor_linked,
  donor_name,
  opportunity_type,
  opportunity_score,
  execution_stress_score,
  donor_perspective,
  firm_perspective,
  implementer_perspective,
  opportunity_window,
  years_in_portfolio,
  pc1_revision_count
)
VALUES

-- ============================================================
-- FEDERAL PSDP — SECTOR: WATER / DAMS (6 schemes)
-- ============================================================

(
  'PSDP-2024-001',
  'Dasu Hydropower Project Phase-I',
  'WAPDA',
  'WAPDA – Dasu HPP PMO',
  'KP',
  'Upper Kohistan',
  'Water/Dams',
  'Hydropower',
  'federal_psdp',
  '2024-25',
  95.0,
  42.0,
  28.5,
  30.00,   -- 28.5/95.0*100
  66.5,    -- 95.0 - 28.5
  480.0,
  'early_implementation',
  'high',
  true,
  true,
  true,
  ARRAY['physical_lag','cost_overrun','extension_risk','safeguard_compliance'],
  true,
  'World Bank / IDA',
  'supervision',
  82.0,
  78.0,
  'World Bank scrutinising safeguard compliance and resettlement progress; disbursement at risk if quarterly benchmarks missed.',
  'Supervision contract active and significant; track tender renewals on WAPDA procurement portal. Position early.',
  'Resettlement of affected communities still unresolved; tunnelling in complex geology causing delays.',
  'Supervision consultancy renewal expected FY2025-26; RPF compliance review also likely.',
  6,
  2
),

(
  'PSDP-2024-002',
  'Diamer Basha Dam',
  'WAPDA',
  'WAPDA – Basha Dam PMO',
  'GB',
  'Diamer',
  'Water/Dams',
  'Storage Dam',
  'federal_psdp',
  '2024-25',
  120.0,
  35.0,
  22.0,
  18.33,   -- 22.0/120.0*100
  98.0,    -- 120.0 - 22.0
  1450.0,
  'mobilization',
  'critical',
  true,
  true,
  true,
  ARRAY['land_acquisition','slow_disbursement','geotechnical_risk','political_dispute'],
  false,
  NULL,
  'supervision',
  90.0,
  88.0,
  'No multilateral finance; entirely GoP-funded. AIIB approach under discussion but not confirmed.',
  'Landmark national project — supervision and monitoring packages expected to be large. Monitor NHA/WAPDA tenders.',
  'Land acquisition and resettlement in remote GB terrain is the primary bottleneck; security access restrictions.',
  'Multiple supervision and PMC packages anticipated over the construction lifecycle.',
  8,
  3
),

(
  'PSDP-2024-003',
  'Mohmand Dam Hydropower Project',
  'WAPDA',
  'WAPDA – Mohmand Dam PMO',
  'KP',
  'Mohmand',
  'Water/Dams',
  'Hydropower',
  'federal_psdp',
  '2024-25',
  45.0,
  28.0,
  18.0,
  40.00,   -- 18.0/45.0*100
  27.0,    -- 45.0 - 18.0
  310.0,
  'early_implementation',
  'high',
  false,
  false,
  true,
  ARRAY['physical_lag','loan_drawdown_risk'],
  true,
  'China EXIM Bank',
  'supervision',
  75.0,
  60.0,
  'China EXIM Bank monitoring disbursement schedule; tied procurement constraints limiting sub-contractor competition.',
  'EXIM-financed project — supervision likely tied; explore sub-consulting with Chinese lead. PMU access key.',
  'Civil works in active tribal area; security protocols add 15–20% to programme timeline.',
  'Environmental monitoring and social safeguard contracts expected Q3 2025.',
  5,
  1
),

(
  'PSDP-2024-004',
  'Tarbela 5th Extension Hydropower',
  'WAPDA',
  'WAPDA – Tarbela PMO',
  'KP',
  'Haripur',
  'Water/Dams',
  'Hydropower',
  'federal_psdp',
  '2024-25',
  28.0,
  24.0,
  19.6,
  70.00,   -- 19.6/28.0*100
  8.4,     -- 28.0 - 19.6
  175.0,
  'mid_implementation',
  'medium',
  false,
  false,
  false,
  ARRAY['physical_lag'],
  true,
  'World Bank',
  'supervision',
  55.0,
  30.0,
  'World Bank tracking steady progress; safeguard compliance satisfactory. Final disbursement tranche expected FY2025.',
  'Project approaching completion; limited new entry opportunity. Track follow-on pipeline.',
  'Tunnel works substantially complete; electromechanical installation ongoing. Minor commissioning delays expected.',
  'Commissioning support and close-out consultancy may arise in FY2025-26.',
  7,
  1
),

(
  'PSDP-2024-005',
  'Kachhi Canal Project Phase-II',
  'IRSA',
  'IRSA / Punjab Irrigation',
  'Balochistan',
  'Dera Bugti',
  'Water/Dams',
  'Irrigation Canal',
  'federal_psdp',
  '2024-25',
  18.5,
  9.0,
  5.5,
  29.73,   -- 5.5/18.5*100
  13.0,    -- 18.5 - 5.5
  95.0,
  'early_implementation',
  'high',
  true,
  false,
  true,
  ARRAY['slow_disbursement','land_acquisition','security_access'],
  false,
  NULL,
  'supervision',
  80.0,
  75.0,
  'No donor; GoP-financed. Balochistan politics regularly disrupt field access.',
  'PMC and supervision opportunities exist. Engage IRSA and Balochistan Irrigation Dept simultaneously.',
  'Canal alignment crosses disputed tribal land; contractor mobilisation repeatedly suspended.',
  'Independent verification assignment expected ahead of Phase-III PC-1 preparation.',
  9,
  3
),

(
  'PSDP-2024-006',
  'Rainee Canal Project',
  'MoWR',
  'Sindh Irrigation Department',
  'Sindh',
  'Ghotki',
  'Water/Dams',
  'Irrigation Canal',
  'federal_psdp',
  '2024-25',
  22.0,
  12.0,
  7.0,
  31.82,   -- 7.0/22.0*100
  15.0,    -- 22.0 - 7.0
  110.0,
  'early_implementation',
  'high',
  true,
  false,
  true,
  ARRAY['slow_disbursement','contractor_default','procurement_delay'],
  false,
  NULL,
  'supervision',
  72.0,
  68.0,
  'Finance Division flagging under-utilisation; project at risk of budget cut in mid-year review.',
  'Supervision and quality-assurance opportunity exists; contact Sindh Irrigation PMU.',
  'Contractor replaced mid-project; remobilisation causing 8-month delay.',
  'Construction supervision re-tender expected following contractor default settlement.',
  7,
  2
),

-- ============================================================
-- FEDERAL PSDP — SECTOR: TRANSPORT / ROADS (8 schemes)
-- ============================================================

(
  'PSDP-2024-010',
  'Peshawar-DI Khan Motorway (M-14)',
  'NHA',
  'National Highway Authority',
  'KP',
  'Multiple',
  'Transport',
  'Motorway',
  'federal_psdp',
  '2024-25',
  38.0,
  30.0,
  22.8,
  60.00,   -- 22.8/38.0*100
  15.2,    -- 38.0 - 22.8
  195.0,
  'mid_implementation',
  'medium',
  false,
  false,
  false,
  ARRAY['physical_lag'],
  false,
  NULL,
  'none',
  55.0,
  45.0,
  'No donor; NHA bond-financed. Progress broadly on track.',
  'Limited consulting opportunity at this stage; track follow-on O&M tender.',
  'Earthworks complete on 70% of alignment; bridge works ongoing at 3 major crossings.',
  'Toll management consultancy expected on completion (est. FY2026).',
  4,
  0
),

(
  'PSDP-2024-011',
  'Sukkur-Hyderabad Motorway (M-6)',
  'NHA',
  'National Highway Authority',
  'Sindh',
  'Multiple',
  'Transport',
  'Motorway',
  'federal_psdp',
  '2024-25',
  32.0,
  16.0,
  9.6,
  30.00,   -- 9.6/32.0*100
  22.4,    -- 32.0 - 9.6
  160.0,
  'early_implementation',
  'high',
  true,
  false,
  false,
  ARRAY['slow_disbursement','land_acquisition','contractor_capacity'],
  false,
  NULL,
  'supervision',
  65.0,
  68.0,
  'No donor. Finance Division considering deferring FY2025-26 allocation pending execution improvement.',
  'Construction supervision contract likely to be re-scoped; engage NHA contracts wing.',
  'Land acquisition for 40 km still pending; PPP structure under renegotiation.',
  'Independent PPP review and restructuring advisory expected Q2 FY2025.',
  3,
  1
),

(
  'PSDP-2024-012',
  'Lahore-Sialkot Motorway Extension',
  'NHA',
  'National Highway Authority',
  'Punjab',
  'Sialkot',
  'Transport',
  'Motorway',
  'federal_psdp',
  '2024-25',
  15.0,
  13.0,
  10.5,
  70.00,   -- 10.5/15.0*100
  4.5,     -- 15.0 - 10.5
  72.0,
  'mid_implementation',
  'low',
  false,
  false,
  false,
  ARRAY[]::text[],
  false,
  NULL,
  'none',
  40.0,
  30.0,
  'Good execution; no donor concerns.',
  'Limited new consulting opportunity. O&M tender may arise post-completion.',
  'Works on schedule; final bridge overlay expected Q4 FY2025.',
  'O&M and toll operations consultancy post-completion.',
  3,
  0
),

(
  'PSDP-2024-013',
  'Hakla-DI Khan Motorway (M-14 Section)',
  'NHA',
  'National Highway Authority',
  'KP',
  'Mianwali',
  'Transport',
  'Motorway',
  'federal_psdp',
  '2024-25',
  25.0,
  22.0,
  17.5,
  70.00,   -- 17.5/25.0*100
  7.5,     -- 25.0 - 17.5
  128.0,
  'completion',
  'medium',
  false,
  false,
  false,
  ARRAY[]::text[],
  false,
  NULL,
  'none',
  45.0,
  30.0,
  'On track; no donor complications.',
  'Final commissioning and defect liability period beginning; limited entry window.',
  'Finishing works and pavement markings ongoing; operational by Q1 FY2026.',
  NULL,
  5,
  0
),

(
  'PSDP-2024-014',
  'Karachi Northern Bypass',
  'NHA',
  'National Highway Authority',
  'Sindh',
  'Karachi',
  'Transport',
  'Bypass Road',
  'federal_psdp',
  '2024-25',
  12.0,
  6.0,
  3.6,
  30.00,   -- 3.6/12.0*100
  8.4,     -- 12.0 - 3.6
  58.0,
  'early_implementation',
  'high',
  true,
  false,
  false,
  ARRAY['land_acquisition','utility_shifting','slow_disbursement'],
  false,
  NULL,
  'supervision',
  70.0,
  70.0,
  'No donor. Finance Division tracking due to urban displacement concerns.',
  'Supervision and utility-shifting advisory opportunity; engage NHA Karachi office.',
  'Utility relocation (SSGC, SSWB lines) causing repeated site stoppages.',
  'Utility relocation oversight consultancy expected Q1 FY2025-26.',
  3,
  1
),

(
  'PSDP-2024-015',
  'Zhob-Quetta N-50 Highway',
  'NHA',
  'National Highway Authority',
  'Balochistan',
  'Zhob',
  'Transport',
  'National Highway',
  'federal_psdp',
  '2024-25',
  20.0,
  10.0,
  6.0,
  30.00,   -- 6.0/20.0*100
  14.0,    -- 20.0 - 6.0
  95.0,
  'early_implementation',
  'critical',
  true,
  true,
  true,
  ARRAY['security_access','land_acquisition','cost_overrun','extension_risk'],
  false,
  NULL,
  'supervision',
  85.0,
  88.0,
  'No donor; purely GoP. Security situation in Zhob district causing cascading delays.',
  'High-risk project with limited safe field access. Desk-based supervision advisory possible.',
  'Active security threats in 3 districts along alignment; contractor convoy requirements add 25% cost.',
  'Security and risk management advisory may be scoped separately from main supervision.',
  6,
  2
),

(
  'PSDP-2024-016',
  'Gilgit-Skardu Road (Karakoram)',
  'NHA',
  'National Highway Authority',
  'GB',
  'Gilgit',
  'Transport',
  'Strategic Road',
  'federal_psdp',
  '2024-25',
  18.0,
  9.0,
  5.4,
  30.00,   -- 5.4/18.0*100
  12.6,    -- 18.0 - 5.4
  88.0,
  'early_implementation',
  'high',
  true,
  false,
  false,
  ARRAY['geological_hazard','weather_window','slow_disbursement'],
  false,
  NULL,
  'supervision',
  78.0,
  70.0,
  'No donor; strategic importance to CPEC. Geological survey needed before phase acceleration.',
  'Geo-hazard assessment and supervision opportunity; limited working season (May–October).',
  'Seasonal construction window (6 months) means effective progress rate is half of comparable projects.',
  'Geotechnical risk assessment and slope-stabilisation advisory expected FY2025.',
  4,
  1
),

(
  'PSDP-2024-017',
  'Lahore Ring Road Southern Loop',
  'NHA',
  'Punjab Roads and Transport Authority',
  'Punjab',
  'Lahore',
  'Transport',
  'Ring Road',
  'federal_psdp',
  '2024-25',
  22.0,
  19.0,
  15.4,
  70.00,   -- 15.4/22.0*100
  6.6,     -- 22.0 - 15.4
  105.0,
  'mid_implementation',
  'medium',
  false,
  false,
  false,
  ARRAY[]::text[],
  false,
  NULL,
  'none',
  48.0,
  30.0,
  'No donor complications; Punjab financing solid.',
  'Limited new opportunity; track O&M and ITS contract coming post-completion.',
  'Structural works largely complete; ITS and toll plaza fit-out ongoing.',
  'ITS (intelligent transport system) advisory and toll system tender expected Q2 FY2026.',
  4,
  0
),

-- ============================================================
-- FEDERAL PSDP — SECTOR: ENERGY (6 schemes)
-- ============================================================

(
  'PSDP-2024-020',
  'NTDC 765kV Transmission Project',
  'NTDC',
  'National Transmission and Despatch Company',
  'Punjab',
  'Multiple',
  'Energy',
  'Power Transmission',
  'federal_psdp',
  '2024-25',
  28.0,
  18.0,
  11.2,
  40.00,   -- 11.2/28.0*100
  16.8,    -- 28.0 - 11.2
  145.0,
  'early_implementation',
  'medium',
  false,
  false,
  false,
  ARRAY['procurement_delay','right_of_way'],
  true,
  'ADB',
  'supervision',
  60.0,
  52.0,
  'ADB satisfied with safeguard process; right-of-way acquisition slightly behind schedule.',
  'Supervision contract active; additional environmental monitoring scope possible.',
  'High-voltage tower erection requires specialised crews; domestic contractor capacity thin.',
  'Environmental and social safeguard monitoring assignment renewal expected.',
  3,
  0
),

(
  'PSDP-2024-021',
  'Quaid-e-Azam Solar Park Extension',
  'AEDB',
  'Quaid-e-Azam Solar (Pvt) Ltd',
  'Punjab',
  'Bahawalpur',
  'Energy',
  'Solar Power',
  'federal_psdp',
  '2024-25',
  15.0,
  13.0,
  10.5,
  70.00,   -- 10.5/15.0*100
  4.5,     -- 15.0 - 10.5
  72.0,
  'completion',
  'low',
  false,
  false,
  false,
  ARRAY[]::text[],
  false,
  NULL,
  'none',
  38.0,
  30.0,
  'On track; no donor concerns. Awaiting grid interconnection clearance.',
  'Limited new opportunity; track O&M performance contract and grid study.',
  'Panel installation complete; commissioning testing ongoing. Grid stability study needed.',
  'Grid integration study and O&M optimisation advisory expected post-commissioning.',
  3,
  0
),

(
  'PSDP-2024-022',
  'Thar Coal Block-II Power Complex',
  'MoE',
  'SECMC / HUBCO',
  'Sindh',
  'Tharparkar',
  'Energy',
  'Coal Power',
  'federal_psdp',
  '2024-25',
  42.0,
  40.0,
  33.6,
  80.00,   -- 33.6/42.0*100
  8.4,     -- 42.0 - 33.6
  230.0,
  'mid_implementation',
  'medium',
  false,
  false,
  true,
  ARRAY['environmental_compliance'],
  true,
  'China EXIM Bank',
  'none',
  45.0,
  20.0,
  'China EXIM satisfied with draw-down pace; environmental permit renewal pending.',
  'Limited TA opportunity; social impact monitoring niche for environment firms.',
  'Mining-power integration on track; lignite quality variability causing minor efficiency adjustments.',
  'Environmental compliance and community impact monitoring niche.',
  6,
  1
),

(
  'PSDP-2024-023',
  'Matiari-Lahore HVDC Transmission Line',
  'NTDC',
  'National Transmission and Despatch Company',
  'Punjab',
  'Multiple',
  'Energy',
  'HVDC Transmission',
  'federal_psdp',
  '2024-25',
  35.0,
  34.0,
  30.1,
  86.00,   -- 30.1/35.0*100
  4.9,     -- 35.0 - 30.1
  165.0,
  'completion',
  'low',
  false,
  false,
  false,
  ARRAY[]::text[],
  true,
  'China EXIM Bank',
  'none',
  35.0,
  14.0,
  'China EXIM Bank very satisfied; project near commissioning.',
  'Project in defect liability period. No new consulting entry.',
  'Testing and commissioning underway; full commercial operation expected Q2 FY2025.',
  NULL,
  7,
  0
),

(
  'PSDP-2024-024',
  'Wind Power Projects Sindh Coastal',
  'AEDB',
  'AEDB / Private IPPs',
  'Sindh',
  'Thatta',
  'Energy',
  'Wind Power',
  'federal_psdp',
  '2024-25',
  8.0,
  4.0,
  2.4,
  30.00,   -- 2.4/8.0*100
  5.6,     -- 8.0 - 2.4
  42.0,
  'early_implementation',
  'high',
  true,
  false,
  false,
  ARRAY['grid_connection_delay','financial_close_risk'],
  false,
  NULL,
  'supervision',
  68.0,
  70.0,
  'No GoP donor; private IPP scheme. GoP land allocation disputes stalling financial close.',
  'Due diligence and feasibility advisory possible for prospective equity investors.',
  'Grid connection agreement with NTDC not yet signed; project stalled at financial close stage.',
  'Independent technical advisory for IPP investors expected.',
  2,
  1
),

(
  'PSDP-2024-025',
  'Neelum-Jhelum Hydropower Remedial Works',
  'WAPDA',
  'WAPDA – NJ PMO',
  'AJK',
  'Muzaffarabad',
  'Energy',
  'Hydropower',
  'federal_psdp',
  '2024-25',
  12.0,
  6.5,
  3.6,
  30.00,   -- 3.6/12.0*100
  8.4,     -- 12.0 - 3.6
  62.0,
  'early_implementation',
  'critical',
  true,
  true,
  true,
  ARRAY['structural_defect','legal_dispute','contractor_default','extension_risk'],
  false,
  NULL,
  'ta_opportunity',
  88.0,
  85.0,
  'No multilateral donor. GoP committed to full remediation to restore 969 MW generation.',
  'Independent technical assessment and dispute resolution advisory — high-value niche.',
  'Tunnel cracks require full de-watering and lining remediation; contractor in arbitration with WAPDA.',
  'Technical investigation and arbitration support advisory expected imminently.',
  4,
  3
),

-- ============================================================
-- FEDERAL PSDP — SECTOR: HEALTH (5 schemes)
-- ============================================================

(
  'PSDP-2024-030',
  'PIMS Islamabad Expansion Phase-II',
  'NHS',
  'Pakistan Institute of Medical Sciences',
  'ICT',
  'Islamabad',
  'Health',
  'Tertiary Healthcare',
  'federal_psdp',
  '2024-25',
  8.5,
  7.0,
  5.1,
  60.00,   -- 5.1/8.5*100
  3.4,     -- 8.5 - 5.1
  42.0,
  'mid_implementation',
  'medium',
  false,
  false,
  false,
  ARRAY['procurement_delay'],
  false,
  NULL,
  'none',
  58.0,
  40.0,
  'MoNHS monitoring closely; Phase-III PC-1 under preparation.',
  'Medical equipment procurement advisory niche for upcoming Phase-III.',
  'Civil works 65% complete; medical equipment procurement delayed by import LC issues.',
  'Medical equipment procurement and commissioning advisory for Phase-III.',
  3,
  1
),

(
  'PSDP-2024-031',
  'National Institute of Child Health Karachi',
  'NHS',
  'Department of Health Sindh',
  'Sindh',
  'Karachi',
  'Health',
  'Child Health',
  'federal_psdp',
  '2024-25',
  4.2,
  2.0,
  1.3,
  30.95,   -- 1.3/4.2*100
  2.9,     -- 4.2 - 1.3
  22.0,
  'early_implementation',
  'high',
  true,
  false,
  false,
  ARRAY['slow_disbursement','pmu_weakness'],
  false,
  NULL,
  'supervision',
  72.0,
  69.0,
  'MoNHS tracking; Sindh health dept capacity constraints flagged.',
  'Supervision and health systems advisory opportunity exists.',
  'PMU understaffed; contractor mobilisation delayed by 4 months.',
  'Construction supervision and quality assurance advisory.',
  2,
  1
),

(
  'PSDP-2024-032',
  'Pakistan Medical Corps Hospital Rawalpindi',
  'MoD',
  'Military Engineering Services',
  'Punjab',
  'Rawalpindi',
  'Health',
  'Military Healthcare',
  'federal_psdp',
  '2024-25',
  3.8,
  3.5,
  2.7,
  71.05,   -- 2.7/3.8*100
  1.1,     -- 3.8 - 2.7
  18.5,
  'completion',
  'low',
  false,
  false,
  false,
  ARRAY[]::text[],
  false,
  NULL,
  'none',
  30.0,
  29.0,
  NULL,
  'Closed procurement; MES manages internally. No external consulting entry.',
  'Works well advanced; operational commissioning expected Q1 FY2025.',
  NULL,
  2,
  0
),

(
  'PSDP-2024-033',
  'Primary Healthcare Programme KP (PDMA)',
  'NHSR&C',
  'Health Department KP / PDMA',
  'KP',
  'Multiple',
  'Health',
  'Primary Healthcare',
  'federal_psdp',
  '2024-25',
  6.0,
  3.0,
  1.8,
  30.00,   -- 1.8/6.0*100
  4.2,     -- 6.0 - 1.8
  28.0,
  'early_implementation',
  'high',
  true,
  false,
  false,
  ARRAY['slow_disbursement','post_flood_context','pmu_weakness'],
  true,
  'USAID',
  'monitoring_evaluation',
  76.0,
  70.0,
  'USAID requiring independent verification of beneficiary reach data before next tranche.',
  'M&E assignment very likely; USAID-registered firms preferred. Track USAID Pakistan procurements.',
  'Post-flood reconstruction context adds logistical complexity in southern KP districts.',
  'USAID-funded M&E contract expected Q2 FY2025.',
  2,
  0
),

(
  'PSDP-2024-034',
  'Nutrition Programme Balochistan',
  'NHSR&C',
  'Nutrition Wing – Ministry of NHSR&C',
  'Balochistan',
  'Multiple',
  'Health',
  'Nutrition',
  'federal_psdp',
  '2024-25',
  3.5,
  1.2,
  0.7,
  20.00,   -- 0.7/3.5*100
  2.8,     -- 3.5 - 0.7
  16.0,
  'mobilization',
  'critical',
  true,
  false,
  false,
  ARRAY['slow_disbursement','capacity_gap','supply_chain_failure'],
  true,
  'UNICEF/WFP',
  'ta_opportunity',
  88.0,
  88.0,
  'UNICEF/WFP co-financing conditional on improved delivery systems; supply chain TA explicitly required.',
  'TA for supply-chain and CMAM system design is explicitly scoped. Pursue UNICEF or WFP sub-contract.',
  'Severe acute malnutrition rates in Balochistan among highest globally; delivery mechanism weak.',
  'Supply chain TA and nutrition programme design assignment expected imminently (UNICEF-funded).',
  2,
  1
),

-- ============================================================
-- FEDERAL PSDP — SECTOR: EDUCATION (5 schemes)
-- ============================================================

(
  'PSDP-2024-040',
  'HEC National Centres for Big Data',
  'HEC',
  'Higher Education Commission',
  'ICT',
  'Islamabad',
  'Education',
  'Higher Education',
  'federal_psdp',
  '2024-25',
  5.5,
  4.5,
  3.3,
  60.00,   -- 3.3/5.5*100
  2.2,     -- 5.5 - 3.3
  26.0,
  'mid_implementation',
  'low',
  false,
  false,
  false,
  ARRAY[]::text[],
  false,
  NULL,
  'none',
  42.0,
  40.0,
  NULL,
  'Limited entry window; HEC manages ICT procurement in-house.',
  'Data centre fit-out and software licensing ongoing; capacity building curriculum in development.',
  'Curriculum advisory and data governance framework assignment possible.',
  2,
  0
),

(
  'PSDP-2024-041',
  'Federal College of Education Islamabad',
  'MoFE',
  'Federal Directorate of Education',
  'ICT',
  'Islamabad',
  'Education',
  'Teacher Education',
  'federal_psdp',
  '2024-25',
  2.8,
  1.4,
  0.8,
  28.57,   -- 0.8/2.8*100
  2.0,     -- 2.8 - 0.8
  14.0,
  'early_implementation',
  'medium',
  true,
  false,
  false,
  ARRAY['slow_disbursement','procurement_delay'],
  false,
  NULL,
  'none',
  60.0,
  71.0,
  NULL,
  'Civil works tender recently re-issued; limited near-term consulting entry.',
  'Contractor re-tendering after initial contract terminated; 7-month schedule setback.',
  'Construction advisory if re-tender stalls again.',
  2,
  1
),

(
  'PSDP-2024-042',
  'TVET Sector Support Programme (NAVTTC)',
  'NAVTTC',
  'National Vocational and Technical Training Commission',
  'ICT',
  'Nationwide',
  'Education',
  'TVET',
  'federal_psdp',
  '2024-25',
  4.0,
  2.4,
  1.6,
  40.00,   -- 1.6/4.0*100
  2.4,     -- 4.0 - 1.6
  20.0,
  'early_implementation',
  'medium',
  false,
  false,
  true,
  ARRAY['procurement_delay'],
  true,
  'EU/GIZ',
  'ta_opportunity',
  70.0,
  60.0,
  'EU and GIZ co-financing requires curriculum alignment with EU standards; TA explicitly required.',
  'Curriculum development and TVET quality assurance TA — GIZ or EU procurement channel.',
  'NAVTTC institutional capacity is the main constraint; high staff turnover in planning wing.',
  'GIZ-funded curriculum and quality assurance TA expected Q3 FY2025.',
  3,
  1
),

(
  'PSDP-2024-043',
  'Allama Iqbal Open University Distance Learning',
  'HEC',
  'Allama Iqbal Open University',
  'Punjab',
  'Islamabad',
  'Education',
  'Distance Education',
  'federal_psdp',
  '2024-25',
  3.2,
  3.0,
  2.2,
  68.75,   -- 2.2/3.2*100
  1.0,     -- 3.2 - 2.2
  16.0,
  'mid_implementation',
  'low',
  false,
  false,
  false,
  ARRAY[]::text[],
  false,
  NULL,
  'none',
  38.0,
  31.0,
  NULL,
  'LMS platform and content development well advanced; limited new entry.',
  'Content digitisation and platform deployment on schedule.',
  NULL,
  2,
  0
),

(
  'PSDP-2024-044',
  'Schools Programme KP (Post-Flood Reconstruction)',
  'MoFE',
  'Elementary and Secondary Education KP',
  'KP',
  'Multiple',
  'Education',
  'School Reconstruction',
  'federal_psdp',
  '2024-25',
  6.8,
  3.4,
  2.0,
  29.41,   -- 2.0/6.8*100
  4.8,     -- 6.8 - 2.0
  32.0,
  'early_implementation',
  'high',
  true,
  false,
  false,
  ARRAY['slow_disbursement','post_flood_context','procurement_delay'],
  true,
  'FCDO/EU',
  'monitoring_evaluation',
  80.0,
  71.0,
  'FCDO and EU requiring independent progress verification; results framework M&E mandatory.',
  'M&E firm with KP education experience strongly positioned; track FCDO Pakistan tender.',
  'Post-flood access constraints in southern KP slowing school construction pace.',
  'FCDO-funded independent M&E assignment expected Q1 FY2025-26.',
  2,
  0
),

-- ============================================================
-- FEDERAL PSDP — SECTOR: AGRICULTURE / WATER (5 schemes)
-- ============================================================

(
  'PSDP-2024-050',
  'National Fertilizer Corporation Rehabilitation',
  'MoFAL',
  'National Fertilizer Corporation',
  'Punjab',
  'Multan',
  'Agriculture',
  'Agri-Industry',
  'federal_psdp',
  '2024-25',
  4.5,
  4.0,
  3.2,
  71.11,   -- 3.2/4.5*100
  1.3,     -- 4.5 - 3.2
  22.0,
  'mid_implementation',
  'low',
  false,
  false,
  false,
  ARRAY[]::text[],
  false,
  NULL,
  'none',
  32.0,
  29.0,
  NULL,
  'Plant rehabilitation largely complete; no significant consulting window.',
  'Mechanical rehabilitation of urea plant units well advanced.',
  NULL,
  3,
  0
),

(
  'PSDP-2024-051',
  'National Agriculture Emergency Programme',
  'MoFAL',
  'Ministry of National Food Security',
  'Punjab',
  'Nationwide',
  'Agriculture',
  'Emergency Agriculture',
  'federal_psdp',
  '2024-25',
  10.0,
  5.0,
  3.0,
  30.00,   -- 3.0/10.0*100
  7.0,     -- 10.0 - 3.0
  48.0,
  'early_implementation',
  'high',
  true,
  false,
  false,
  ARRAY['slow_disbursement','policy_flux','disbursement_mechanism'],
  false,
  NULL,
  'supervision',
  72.0,
  70.0,
  'Finance Division flagging poor absorption; scheme design criticised for lack of targeting.',
  'Programme evaluation and redesign advisory likely ahead of PC-1 revision.',
  'Beneficiary selection criteria unclear; subsidy disbursement mechanism contested by provinces.',
  'Programme evaluation and PC-1 revision advisory expected mid FY2025.',
  2,
  1
),

(
  'PSDP-2024-052',
  'Indus River System Authority Projects',
  'IRSA',
  'Indus River System Authority',
  'Sindh',
  'Multiple',
  'Agriculture',
  'River Management',
  'federal_psdp',
  '2024-25',
  7.5,
  4.0,
  2.6,
  34.67,   -- 2.6/7.5*100
  4.9,     -- 7.5 - 2.6
  36.0,
  'early_implementation',
  'high',
  true,
  false,
  false,
  ARRAY['inter_provincial_dispute','slow_disbursement'],
  false,
  NULL,
  'none',
  65.0,
  65.0,
  NULL,
  'Inter-provincial water dispute resolution advisory is a niche for specialised consultants.',
  'IRSA quota disputes between Sindh and Punjab delaying joint works on shared headworks.',
  'Water allocation dispute resolution advisory possible.',
  3,
  1
),

(
  'PSDP-2024-053',
  'Cholistan Development Authority Canal',
  'MoWR',
  'Cholistan Development Authority',
  'Punjab',
  'Bahawalpur',
  'Agriculture',
  'Irrigation Canal',
  'federal_psdp',
  '2024-25',
  18.0,
  7.0,
  4.5,
  25.00,   -- 4.5/18.0*100
  13.5,    -- 18.0 - 4.5
  88.0,
  'early_implementation',
  'high',
  true,
  false,
  true,
  ARRAY['slow_disbursement','land_acquisition','environmental_clearance'],
  false,
  NULL,
  'supervision',
  78.0,
  75.0,
  NULL,
  'Supervision and environmental monitoring opportunity; contact CDA PMU.',
  'Environmental clearance for Cholistan desert corridor still pending; land demarcation disputed.',
  'Environmental clearance and canal design review advisory.',
  5,
  2
),

(
  'PSDP-2024-054',
  'Groundwater Management Punjab',
  'MoFAL',
  'Punjab Irrigation / PCRWR',
  'Punjab',
  'Multiple',
  'Agriculture',
  'Groundwater',
  'federal_psdp',
  '2024-25',
  5.0,
  2.5,
  1.5,
  30.00,   -- 1.5/5.0*100
  3.5,     -- 5.0 - 1.5
  24.0,
  'early_implementation',
  'medium',
  true,
  false,
  false,
  ARRAY['slow_disbursement','data_gaps'],
  true,
  'World Bank',
  'ta_opportunity',
  65.0,
  70.0,
  'World Bank requiring hydrogeological data before disbursement; TA for aquifer monitoring explicitly scoped.',
  'Hydrogeological assessment TA is explicitly required — World Bank channel. Track procurement notice.',
  'Aquifer-level monitoring network not yet established; baseline data gaps delaying loan disbursement.',
  'World Bank-funded hydrogeological TA expected Q2 FY2025.',
  2,
  0
),

-- ============================================================
-- FEDERAL PSDP — SECTOR: SOCIAL PROTECTION (5 schemes)
-- ============================================================

(
  'PSDP-2024-060',
  'Ehsaas Nashonuma (Nutrition Conditional Cash)',
  'Ehsaas',
  'Benazir Income Support Programme',
  'Nationwide',
  NULL,
  'Social Protection',
  'Conditional Cash Transfer',
  'federal_psdp',
  '2024-25',
  12.0,
  11.0,
  8.4,
  70.00,   -- 8.4/12.0*100
  3.6,     -- 12.0 - 8.4
  58.0,
  'mid_implementation',
  'low',
  false,
  false,
  false,
  ARRAY[]::text[],
  true,
  'World Bank',
  'none',
  48.0,
  30.0,
  'World Bank flagship nutrition CCT; strong performance. Phase-II preparation underway.',
  'Limited entry; Phase-II M&E scope under discussion with World Bank.',
  'Beneficiary registration at 85% of target; CNIC verification backlog in rural Sindh.',
  'Phase-II design and M&E framework advisory expected.',
  3,
  0
),

(
  'PSDP-2024-061',
  'BISP Technology Upgrade',
  'BISP',
  'Benazir Income Support Programme',
  'ICT',
  'Islamabad',
  'Social Protection',
  'Social Registry',
  'federal_psdp',
  '2024-25',
  3.5,
  3.2,
  2.5,
  71.43,   -- 2.5/3.5*100
  1.0,     -- 3.5 - 2.5
  17.0,
  'completion',
  'low',
  false,
  false,
  false,
  ARRAY[]::text[],
  false,
  NULL,
  'none',
  35.0,
  29.0,
  NULL,
  'System nearing completion; no significant new consulting window.',
  'NSER 2.0 data migration and new payment management system near operational.',
  NULL,
  2,
  0
),

(
  'PSDP-2024-062',
  'Naya Pakistan Housing Authority Phase-I',
  'NPHDA',
  'Naya Pakistan Housing & Development Authority',
  'Punjab',
  'Multiple',
  'Social Protection',
  'Affordable Housing',
  'federal_psdp',
  '2024-25',
  15.0,
  7.0,
  4.5,
  30.00,   -- 4.5/15.0*100
  10.5,    -- 15.0 - 4.5
  72.0,
  'early_implementation',
  'high',
  true,
  true,
  true,
  ARRAY['slow_disbursement','land_acquisition','financial_model_flux','contractor_capacity'],
  false,
  NULL,
  'supervision',
  70.0,
  70.0,
  NULL,
  'Programme redesign and PMO advisory opportunity; NPHDA actively seeking support.',
  'Land identification and acquisition stalled in 9 of 15 sites; PPP financial model under revision.',
  'Programme PMO and housing finance advisory expected.',
  4,
  2
),

(
  'PSDP-2024-063',
  'Social Health Protection Initiative',
  'NHS',
  'State Life / NHS',
  'Nationwide',
  NULL,
  'Social Protection',
  'Health Insurance',
  'federal_psdp',
  '2024-25',
  6.0,
  3.5,
  2.4,
  40.00,   -- 2.4/6.0*100
  3.6,     -- 6.0 - 2.4
  30.0,
  'early_implementation',
  'medium',
  false,
  false,
  false,
  ARRAY['slow_disbursement'],
  true,
  'ADB',
  'monitoring_evaluation',
  62.0,
  60.0,
  'ADB requiring independent assessment of claims management system before next tranche.',
  'Health insurance M&E and claims audit advisory — ADB procurement channel.',
  'Claims fraud detection system not yet operational; manual verification causing bottlenecks.',
  'ADB-funded claims system and M&E advisory expected Q3 FY2025.',
  2,
  0
),

(
  'PSDP-2024-064',
  'Climate Resilient Livelihoods Programme',
  'MoCC',
  'Pakistan Climate Change Authority',
  'Sindh',
  'Multiple',
  'Social Protection',
  'Climate Adaptation',
  'federal_psdp',
  '2024-25',
  8.0,
  4.0,
  2.4,
  30.00,   -- 2.4/8.0*100
  5.6,     -- 8.0 - 2.4
  38.0,
  'early_implementation',
  'high',
  true,
  false,
  false,
  ARRAY['slow_disbursement','institutional_fragmentation'],
  true,
  'GCF/UNDP',
  'ta_opportunity',
  82.0,
  70.0,
  'GCF requiring results-based management framework; UNDP requiring independent verification.',
  'Climate adaptation TA and results framework advisory — GCF and UNDP channels.',
  'Cross-ministry coordination between MoCC and provincial adaptation bodies weak.',
  'GCF-funded results management and adaptation TA expected Q2 FY2025.',
  2,
  1
),

-- ============================================================
-- FEDERAL PSDP — SECTOR: DIGITAL / GOVERNANCE (5 schemes)
-- ============================================================

(
  'PSDP-2024-070',
  'Digital Pakistan Vision NITB',
  'MoIT',
  'National Information Technology Board',
  'ICT',
  'Islamabad',
  'Digital/Governance',
  'Digital Infrastructure',
  'federal_psdp',
  '2024-25',
  4.0,
  3.2,
  2.4,
  60.00,   -- 2.4/4.0*100
  1.6,     -- 4.0 - 2.4
  20.0,
  'mid_implementation',
  'medium',
  false,
  false,
  false,
  ARRAY[]::text[],
  false,
  NULL,
  'none',
  52.0,
  40.0,
  NULL,
  'Digital infrastructure advisory possible for cloud migration component.',
  'Cloud migration of federal e-services underway; cybersecurity audit pending.',
  'Cybersecurity assessment advisory expected.',
  2,
  0
),

(
  'PSDP-2024-071',
  'E-Government Directorate NADRA Expansion',
  'MoI',
  'NADRA',
  'ICT',
  'Islamabad',
  'Digital/Governance',
  'Identity Management',
  'federal_psdp',
  '2024-25',
  3.2,
  2.9,
  2.2,
  68.75,   -- 2.2/3.2*100
  1.0,     -- 3.2 - 2.2
  16.0,
  'completion',
  'low',
  false,
  false,
  false,
  ARRAY[]::text[],
  false,
  NULL,
  'none',
  30.0,
  31.0,
  NULL,
  'NADRA expansion nearing completion; no significant entry window.',
  'Biometric registration expansion in AJK and GB components nearly complete.',
  NULL,
  2,
  0
),

(
  'PSDP-2024-072',
  'Integrated Financial Management System',
  'Finance',
  'Controller General of Accounts',
  'ICT',
  'Islamabad',
  'Digital/Governance',
  'Public Financial Management',
  'federal_psdp',
  '2024-25',
  2.5,
  1.2,
  0.8,
  32.00,   -- 0.8/2.5*100
  1.7,     -- 2.5 - 0.8
  12.0,
  'early_implementation',
  'medium',
  true,
  false,
  false,
  ARRAY['slow_disbursement','change_management_risk'],
  false,
  NULL,
  'ta_opportunity',
  55.0,
  68.0,
  NULL,
  'SAP/Oracle implementation advisory and change management TA opportunity.',
  'IFMS rollout stalled on inter-ministry data standards alignment; change management resistance high.',
  'IFMS implementation and change management TA.',
  2,
  1
),

(
  'PSDP-2024-073',
  'National Emergency Operations Centre',
  'NDMA',
  'National Disaster Management Authority',
  'ICT',
  'Islamabad',
  'Digital/Governance',
  'Disaster Management',
  'federal_psdp',
  '2024-25',
  3.8,
  3.4,
  2.7,
  71.05,   -- 2.7/3.8*100
  1.1,     -- 3.8 - 2.7
  18.5,
  'mid_implementation',
  'low',
  false,
  false,
  false,
  ARRAY[]::text[],
  false,
  NULL,
  'none',
  42.0,
  29.0,
  NULL,
  'EOC systems integration nearing completion; no major consulting window.',
  'Communications integration and early warning system installation well advanced.',
  NULL,
  2,
  0
),

(
  'PSDP-2024-074',
  'Right of Access to Information System',
  'Cabinet',
  'Pakistan Information Commission',
  'ICT',
  'Islamabad',
  'Digital/Governance',
  'Governance',
  'federal_psdp',
  '2024-25',
  1.5,
  0.8,
  0.5,
  33.33,   -- 0.5/1.5*100
  1.0,     -- 1.5 - 0.5
  7.5,
  'early_implementation',
  'medium',
  true,
  false,
  false,
  ARRAY['slow_disbursement','institutional_capacity'],
  false,
  NULL,
  'ta_opportunity',
  55.0,
  67.0,
  NULL,
  'RTI portal advisory and capacity building TA — small but strategically visible.',
  'Pakistan Information Commission lacks technical staff; portal development stalled.',
  'RTI portal development and PIC capacity building advisory.',
  2,
  1
),

-- ============================================================
-- PROVINCIAL ADP — PUNJAB (10 schemes)
-- ============================================================

(
  'ADP-PJB-001',
  'Punjab Safe Cities Authority Phase-II',
  'Home Department Punjab',
  'Punjab Safe Cities Authority',
  'Punjab',
  'Lahore',
  'Governance',
  'Public Safety',
  'provincial_adp',
  '2024-25',
  8.0,
  7.0,
  5.6,
  70.00,   -- 5.6/8.0*100
  2.4,     -- 8.0 - 5.6
  38.0,
  'mid_implementation',
  'medium',
  false,
  false,
  false,
  ARRAY[]::text[],
  false,
  NULL,
  'none',
  42.0,
  30.0,
  NULL,
  'CCTV network expansion well advanced; limited new consulting entry.',
  'Phase-II CCTV rollout to Rawalpindi and Faisalabad ongoing.',
  NULL,
  3,
  0
),

(
  'ADP-PJB-002',
  'Children Hospital Lahore Extension',
  'Health Department Punjab',
  'The Children''s Hospital Lahore',
  'Punjab',
  'Lahore',
  'Health',
  'Tertiary Paediatric',
  'provincial_adp',
  '2024-25',
  4.5,
  2.5,
  1.8,
  40.00,   -- 1.8/4.5*100
  2.7,     -- 4.5 - 1.8
  22.0,
  'early_implementation',
  'high',
  true,
  false,
  false,
  ARRAY['slow_disbursement','procurement_delay'],
  true,
  'JICA',
  'supervision',
  72.0,
  60.0,
  'JICA monitoring closely; quarterly physical progress reporting required.',
  'Supervision advisory opportunity via JICA channel; JV with Japanese firm preferred.',
  'Structural works 35% complete; medical equipment tender not yet issued.',
  'JICA-funded supervision and medical equipment advisory.',
  2,
  1
),

(
  'ADP-PJB-003',
  'Punjab Skills Development Fund',
  'Labour & HR Department Punjab',
  'Punjab Skills Development Fund',
  'Punjab',
  'Multiple',
  'Skills/TVET',
  'Workforce Development',
  'provincial_adp',
  '2024-25',
  6.0,
  5.0,
  3.6,
  60.00,   -- 3.6/6.0*100
  2.4,     -- 6.0 - 3.6
  30.0,
  'mid_implementation',
  'low',
  false,
  false,
  false,
  ARRAY[]::text[],
  true,
  'ADB',
  'monitoring_evaluation',
  50.0,
  40.0,
  'ADB tracking results framework; independent M&E required before next tranche.',
  'M&E assignment expected; ADB procurement channel for PSDF monitoring.',
  'Training provider performance data strong in urban centres; rural data weak.',
  'ADB-funded M&E advisory expected Q2 FY2025.',
  4,
  0
),

(
  'ADP-PJB-004',
  'Punjab School Education Reform',
  'School Education Department Punjab',
  'Punjab Education Foundation / PMIU',
  'Punjab',
  'Multiple',
  'Education',
  'Basic Education',
  'provincial_adp',
  '2024-25',
  12.0,
  10.0,
  7.2,
  60.00,   -- 7.2/12.0*100
  4.8,     -- 12.0 - 7.2
  58.0,
  'mid_implementation',
  'medium',
  false,
  false,
  false,
  ARRAY[]::text[],
  true,
  'FCDO/World Bank',
  'monitoring_evaluation',
  58.0,
  40.0,
  'FCDO and World Bank both requiring independent assessment of learning outcomes.',
  'Learning outcomes M&E and EMIS advisory — significant assignment.',
  'EMIS data quality improving but teacher attendance verification still manual.',
  'FCDO-funded learning outcomes assessment expected Q1 FY2025-26.',
  5,
  1
),

(
  'ADP-PJB-005',
  'Rural Road Programme Punjab',
  'C&W Department Punjab',
  'Punjab Rural Support Programme',
  'Punjab',
  'Multiple',
  'Transport',
  'Rural Roads',
  'provincial_adp',
  '2024-25',
  15.0,
  8.0,
  6.0,
  40.00,   -- 6.0/15.0*100
  9.0,     -- 15.0 - 6.0
  72.0,
  'early_implementation',
  'high',
  true,
  false,
  false,
  ARRAY['slow_disbursement','contractor_capacity','quality_control'],
  false,
  NULL,
  'supervision',
  65.0,
  60.0,
  NULL,
  'Quality assurance and supervision advisory; C&W Punjab has open procurement.',
  'Multiple small contractors with limited capacity; quality defects reported on 12 sites.',
  'Quality assurance and road safety advisory.',
  3,
  1
),

(
  'ADP-PJB-006',
  'Punjab Solar Tube Well Programme',
  'Agriculture Department Punjab',
  'Agriculture Department Punjab',
  'Punjab',
  'Multiple',
  'Agriculture',
  'Irrigation',
  'provincial_adp',
  '2024-25',
  10.0,
  9.0,
  7.0,
  70.00,   -- 7.0/10.0*100
  3.0,     -- 10.0 - 7.0
  48.0,
  'mid_implementation',
  'low',
  false,
  false,
  false,
  ARRAY[]::text[],
  true,
  'World Bank',
  'none',
  42.0,
  30.0,
  'World Bank satisfied with solar conversion rate.',
  'Limited consulting window; World Bank M&E built into project.',
  'Solar conversion of 50,000 diesel tube wells on track; net metering agreements progressing.',
  NULL,
  3,
  0
),

(
  'ADP-PJB-007',
  'Lahore Mass Transit Orange Line Extension',
  'Transport Department Punjab',
  'Lahore Development Authority',
  'Punjab',
  'Lahore',
  'Transport',
  'Urban Rail',
  'provincial_adp',
  '2024-25',
  22.0,
  12.0,
  8.8,
  40.00,   -- 8.8/22.0*100
  13.2,    -- 22.0 - 8.8
  110.0,
  'early_implementation',
  'high',
  true,
  true,
  true,
  ARRAY['land_acquisition','utility_shifting','cost_overrun','extension_risk'],
  false,
  NULL,
  'supervision',
  70.0,
  60.0,
  NULL,
  'Supervision and transit advisory opportunity; LDA procurement open.',
  'Elevated guideway works in dense urban areas causing utility conflicts and community opposition.',
  'Independent tunnel/structural inspection and supervision advisory.',
  4,
  2
),

(
  'ADP-PJB-008',
  'Punjab Intermediate Cities Infrastructure',
  'LG&CD Department Punjab',
  'Punjab Municipal Development Fund Co.',
  'Punjab',
  'Multiple',
  'Water/Sanitation',
  'Urban Water Supply',
  'provincial_adp',
  '2024-25',
  9.0,
  5.0,
  3.6,
  40.00,   -- 3.6/9.0*100
  5.4,     -- 9.0 - 3.6
  44.0,
  'early_implementation',
  'high',
  true,
  false,
  false,
  ARRAY['slow_disbursement','procurement_delay'],
  true,
  'ADB',
  'supervision',
  68.0,
  60.0,
  'ADB requiring progress acceleration; city-level implementation units understaffed.',
  'Supervision advisory via ADB channel; PMDFC PMU actively sourcing support.',
  'Water and sanitation works in 8 intermediate cities; 3 cities significantly behind schedule.',
  'ADB-funded construction supervision and city PMU support advisory.',
  3,
  0
),

(
  'ADP-PJB-009',
  'Chief Minister Kisaan Package',
  'Agriculture Department Punjab',
  'Agriculture Department Punjab',
  'Punjab',
  'Multiple',
  'Agriculture',
  'Subsidy Programme',
  'provincial_adp',
  '2024-25',
  8.0,
  7.5,
  5.6,
  70.00,   -- 5.6/8.0*100
  2.4,     -- 8.0 - 5.6
  38.0,
  'mid_implementation',
  'low',
  false,
  false,
  false,
  ARRAY[]::text[],
  false,
  NULL,
  'none',
  38.0,
  30.0,
  NULL,
  'Subsidy disbursement well advanced; limited consulting entry.',
  'Fertiliser and seed subsidy distribution at 70% of annual target.',
  NULL,
  2,
  0
),

(
  'ADP-PJB-010',
  'Punjab Primary Healthcare Programme',
  'Health Department Punjab',
  'Primary & Secondary Healthcare Dept Punjab',
  'Punjab',
  'Multiple',
  'Health',
  'Primary Healthcare',
  'provincial_adp',
  '2024-25',
  7.5,
  3.5,
  2.25,
  30.00,   -- 2.25/7.5*100
  5.25,    -- 7.5 - 2.25
  36.0,
  'early_implementation',
  'high',
  true,
  false,
  false,
  ARRAY['slow_disbursement','pmu_weakness','supply_chain_failure'],
  true,
  'GIZ/KfW',
  'ta_opportunity',
  75.0,
  70.0,
  'GIZ/KfW co-financing requiring TA for health systems strengthening; explicitly scoped.',
  'Health systems TA via GIZ or KfW channel — high-value assignment. Track KfW Pakistan pipeline.',
  'Basic health units understaffed; medicine supply chain disruption in 6 districts.',
  'GIZ/KfW-funded health systems TA expected Q2 FY2025.',
  3,
  1
),

-- ============================================================
-- PROVINCIAL ADP — SINDH (10 schemes)
-- ============================================================

(
  'ADP-SND-001',
  'Karachi Water and Sewerage Improvement',
  'Local Government Sindh',
  'Karachi Water and Sewerage Board',
  'Sindh',
  'Karachi',
  'Water/Sanitation',
  'Urban Water',
  'provincial_adp',
  '2024-25',
  18.0,
  9.0,
  5.4,
  30.00,   -- 5.4/18.0*100
  12.6,    -- 18.0 - 5.4
  90.0,
  'early_implementation',
  'critical',
  true,
  true,
  true,
  ARRAY['institutional_failure','land_acquisition','slow_disbursement','cost_overrun','extension_risk'],
  true,
  'ADB/World Bank',
  'supervision',
  88.0,
  88.0,
  'ADB and World Bank jointly expressing concern over KWSB institutional governance failures; programme at risk.',
  'Supervision and PMO advisory — critical engagement; ADB and World Bank both have open procurements.',
  'KWSB revenues insufficient to finance O&M; political interference in staffing decisions chronic.',
  'ADB/World Bank co-funded supervision, institutional reform advisory and PMO support expected.',
  6,
  3
),

(
  'ADP-SND-002',
  'Sindh Coastal Community Development',
  'Planning & Development Sindh',
  'Sindh Coastal Development Authority',
  'Sindh',
  'Thatta',
  'Social Protection',
  'Coastal Livelihoods',
  'provincial_adp',
  '2024-25',
  4.5,
  3.8,
  2.7,
  60.00,   -- 2.7/4.5*100
  1.8,     -- 4.5 - 2.7
  22.0,
  'mid_implementation',
  'medium',
  false,
  false,
  false,
  ARRAY[]::text[],
  true,
  'World Bank',
  'none',
  55.0,
  40.0,
  'World Bank tracking livelihoods outcomes; satisfactory progress.',
  'Limited near-term consulting window; Phase-II design may open late FY2025.',
  'Mangrove restoration and fishing community livelihood support on track.',
  'Phase-II design advisory possible late FY2025.',
  3,
  0
),

(
  'ADP-SND-003',
  'Sindh Basic Education Programme',
  'Education Sindh',
  'Sindh Education Foundation',
  'Sindh',
  'Multiple',
  'Education',
  'Basic Education',
  'provincial_adp',
  '2024-25',
  9.0,
  6.5,
  4.5,
  50.00,   -- 4.5/9.0*100
  4.5,     -- 9.0 - 4.5
  44.0,
  'early_implementation',
  'medium',
  false,
  false,
  false,
  ARRAY['procurement_delay'],
  true,
  'EU/USAID',
  'monitoring_evaluation',
  60.0,
  50.0,
  'EU and USAID requiring independent learning assessment; results-based financing trigger approaching.',
  'Learning outcomes M&E and EMIS advisory via EU or USAID channel.',
  'School infrastructure and teacher training components on track; learning outcomes data weak.',
  'EU/USAID-funded independent learning assessment expected Q3 FY2025.',
  4,
  1
),

(
  'ADP-SND-004',
  'People''s Primary Healthcare Initiative',
  'Health Sindh',
  'People''s Primary Healthcare Initiative Sindh',
  'Sindh',
  'Multiple',
  'Health',
  'Primary Healthcare',
  'provincial_adp',
  '2024-25',
  6.5,
  3.8,
  2.6,
  40.00,   -- 2.6/6.5*100
  3.9,     -- 6.5 - 2.6
  32.0,
  'early_implementation',
  'high',
  true,
  false,
  false,
  ARRAY['slow_disbursement','supply_chain_failure'],
  true,
  'UNICEF',
  'supervision',
  75.0,
  60.0,
  'UNICEF requiring supply chain audit before releasing next tranche.',
  'Supply chain audit and health systems advisory via UNICEF channel.',
  'Medicine stockouts in rural Sindh BHUs recurring; cold-chain breakdown in Tharparkar.',
  'UNICEF-funded supply chain audit and advisory expected.',
  3,
  1
),

(
  'ADP-SND-005',
  'Sukkur Barrage Rehabilitation',
  'Irrigation Sindh',
  'Sindh Irrigation and Drainage Authority',
  'Sindh',
  'Sukkur',
  'Water/Dams',
  'Barrage',
  'provincial_adp',
  '2024-25',
  12.0,
  5.5,
  3.6,
  30.00,   -- 3.6/12.0*100
  8.4,     -- 12.0 - 3.6
  58.0,
  'early_implementation',
  'critical',
  true,
  true,
  true,
  ARRAY['structural_defect','slow_disbursement','extension_risk','geotechnical_risk'],
  false,
  NULL,
  'supervision',
  85.0,
  88.0,
  'Finance Division and NDMA both tracking; structural failure risk flagged in recent NDMA assessment.',
  'Structural inspection and remediation supervision — urgent. Contact SIDA directly.',
  'Original 1932 structure showing weir gate corrosion and foundation scour; emergency repairs needed.',
  'Structural remediation supervision and emergency engineering advisory.',
  5,
  2
),

(
  'ADP-SND-006',
  'Sindh Green Revolution Programme',
  'Agriculture Sindh',
  'Agriculture Department Sindh',
  'Sindh',
  'Multiple',
  'Agriculture',
  'Crop Production',
  'provincial_adp',
  '2024-25',
  5.0,
  3.5,
  2.5,
  50.00,   -- 2.5/5.0*100
  2.5,     -- 5.0 - 2.5
  24.0,
  'early_implementation',
  'medium',
  false,
  false,
  false,
  ARRAY[]::text[],
  false,
  NULL,
  'none',
  50.0,
  50.0,
  NULL,
  'Limited consulting entry; agronomy advisory possible.',
  'Seed distribution and soil health programme progressing at average pace.',
  'Agronomy and soil health advisory niche.',
  2,
  0
),

(
  'ADP-SND-007',
  'Hyderabad Development Authority Roads',
  'Works Sindh',
  'Hyderabad Development Authority',
  'Sindh',
  'Hyderabad',
  'Transport',
  'Urban Roads',
  'provincial_adp',
  '2024-25',
  7.0,
  3.5,
  2.1,
  30.00,   -- 2.1/7.0*100
  4.9,     -- 7.0 - 2.1
  34.0,
  'early_implementation',
  'high',
  true,
  false,
  false,
  ARRAY['slow_disbursement','contractor_capacity'],
  false,
  NULL,
  'supervision',
  65.0,
  70.0,
  NULL,
  'Supervision advisory; HDA procurement accessible via Sindh Works Department.',
  'Contractor mobilisation in 3 of 7 road packages delayed by equipment shortage.',
  'Construction quality assurance and supervision.',
  2,
  1
),

(
  'ADP-SND-008',
  'Sindh Social Protection Strategy',
  'Planning Sindh',
  'Sindh Social Protection Authority',
  'Sindh',
  'Multiple',
  'Social Protection',
  'Social Safety Net',
  'provincial_adp',
  '2024-25',
  8.0,
  7.0,
  4.8,
  60.00,   -- 4.8/8.0*100
  3.2,     -- 8.0 - 4.8
  38.0,
  'mid_implementation',
  'low',
  false,
  false,
  false,
  ARRAY[]::text[],
  true,
  'World Bank',
  'none',
  45.0,
  40.0,
  'World Bank satisfied with SSPA institutional development.',
  'Limited near-term consulting entry.',
  'Social registry expansion and grievance redressal mechanism both on track.',
  NULL,
  3,
  0
),

(
  'ADP-SND-009',
  'Sindh Solar Energy Programme',
  'Energy Sindh',
  'Sindh Energy Department',
  'Sindh',
  'Multiple',
  'Energy',
  'Solar Power',
  'provincial_adp',
  '2024-25',
  6.0,
  3.5,
  2.4,
  40.00,   -- 2.4/6.0*100
  3.6,     -- 6.0 - 2.4
  30.0,
  'early_implementation',
  'medium',
  false,
  false,
  false,
  ARRAY['procurement_delay'],
  false,
  NULL,
  'none',
  58.0,
  60.0,
  NULL,
  'Solar mini-grid feasibility and design advisory possible.',
  'Off-grid solar panel procurement for schools and health facilities behind schedule.',
  'Solar mini-grid design advisory for next phase.',
  2,
  0
),

(
  'ADP-SND-010',
  'Tharparkar District Development',
  'Planning Sindh',
  'Tharparkar District Government',
  'Sindh',
  'Tharparkar',
  'Social Protection',
  'District Development',
  'provincial_adp',
  '2024-25',
  5.5,
  2.5,
  1.65,
  30.00,   -- 1.65/5.5*100
  3.85,    -- 5.5 - 1.65
  26.0,
  'early_implementation',
  'critical',
  true,
  false,
  false,
  ARRAY['slow_disbursement','capacity_gap','access_constraints'],
  true,
  'OPEC Fund/IsDB',
  'ta_opportunity',
  88.0,
  70.0,
  'OPEC Fund and IsDB requiring TA for district implementation capacity; explicitly scoped.',
  'District capacity building and programme TA via OPEC Fund or IsDB channel.',
  'District government implementation capacity extremely limited; logistical access poor in monsoon.',
  'OPEC Fund/IsDB-funded district capacity building TA expected.',
  3,
  2
),

-- ============================================================
-- PROVINCIAL ADP — KHYBER PAKHTUNKHWA (10 schemes)
-- ============================================================

(
  'ADP-KP-001',
  'KP Emergency Recovery (Post-2022 Floods)',
  'Planning & Dev KP',
  'PDMA KP / P&D Department',
  'KP',
  'Multiple',
  'Social Protection',
  'Disaster Recovery',
  'provincial_adp',
  '2024-25',
  15.0,
  13.0,
  9.0,
  60.00,   -- 9.0/15.0*100
  6.0,     -- 15.0 - 9.0
  72.0,
  'mid_implementation',
  'medium',
  false,
  false,
  false,
  ARRAY[]::text[],
  true,
  'World Bank/ADB/FCDO',
  'none',
  62.0,
  40.0,
  'Multi-donor programme; satisfactory progress across most components.',
  'Limited new entry; M&E and verification ongoing.',
  'Housing reconstruction 65% complete; livelihood restoration component slower.',
  'Final verification and close-out advisory expected FY2025-26.',
  3,
  0
),

(
  'ADP-KP-002',
  'Khyber Teaching Hospital Expansion',
  'Health KP',
  'Khyber Teaching Hospital',
  'KP',
  'Peshawar',
  'Health',
  'Tertiary Healthcare',
  'provincial_adp',
  '2024-25',
  5.5,
  3.2,
  2.2,
  40.00,   -- 2.2/5.5*100
  3.3,     -- 5.5 - 2.2
  26.0,
  'early_implementation',
  'high',
  true,
  false,
  false,
  ARRAY['slow_disbursement','procurement_delay'],
  false,
  NULL,
  'supervision',
  70.0,
  60.0,
  NULL,
  'Construction supervision and medical equipment advisory; KP Health DG office accessible.',
  'New trauma centre block civil works at 35%; medical equipment tender not issued.',
  'Construction supervision and medical equipment procurement advisory.',
  2,
  1
),

(
  'ADP-KP-003',
  'KP Elementary Education Foundation',
  'Elementary & Secondary Educ KP',
  'KP Elementary Education Foundation',
  'KP',
  'Multiple',
  'Education',
  'Basic Education',
  'provincial_adp',
  '2024-25',
  7.0,
  6.2,
  4.9,
  70.00,   -- 4.9/7.0*100
  2.1,     -- 7.0 - 4.9
  34.0,
  'mid_implementation',
  'low',
  false,
  false,
  false,
  ARRAY[]::text[],
  true,
  'DFID/FCDO',
  'none',
  48.0,
  30.0,
  'FCDO satisfied with school enrolment data; girls'' enrolment KPI met.',
  'Limited new entry; FCDO programme close to target.',
  'Community school programme well embedded in tribal districts.',
  'Close-out evaluation advisory expected FY2025-26.',
  5,
  0
),

(
  'ADP-KP-004',
  'Peshawar Bus Rapid Transit Extension',
  'Transport KP',
  'Peshawar Development Authority',
  'KP',
  'Peshawar',
  'Transport',
  'BRT',
  'provincial_adp',
  '2024-25',
  8.5,
  7.5,
  5.1,
  60.00,   -- 5.1/8.5*100
  3.4,     -- 8.5 - 5.1
  42.0,
  'mid_implementation',
  'medium',
  false,
  false,
  false,
  ARRAY[]::text[],
  true,
  'ADB/JICA',
  'none',
  50.0,
  40.0,
  'ADB and JICA both satisfied; extension corridor works on track.',
  'Limited new entry; civil works advanced.',
  'BRT extension to University Town corridor civil works 60% complete.',
  'O&M advisory post-commissioning.',
  4,
  0
),

(
  'ADP-KP-005',
  'Swat Tourism Development Authority',
  'Tourism KP',
  'Swat Development Authority',
  'KP',
  'Swat',
  'Transport',
  'Tourism Infrastructure',
  'provincial_adp',
  '2024-25',
  4.0,
  2.0,
  1.2,
  30.00,   -- 1.2/4.0*100
  2.8,     -- 4.0 - 1.2
  20.0,
  'early_implementation',
  'high',
  true,
  false,
  false,
  ARRAY['slow_disbursement','environmental_clearance','seasonal_constraint'],
  false,
  NULL,
  'supervision',
  68.0,
  70.0,
  NULL,
  'Tourism infrastructure and environmental advisory; KP Tourism DG accessible.',
  'Mountain road and visitor facility construction restricted to 5-month summer season.',
  'Environmental assessment and tourism infrastructure advisory.',
  2,
  1
),

(
  'ADP-KP-006',
  'KP Tribal Districts Development Programme',
  'Planning KP',
  'Tribal Districts Development Secretariat',
  'KP',
  'Multiple',
  'Social Protection',
  'Merged Districts',
  'provincial_adp',
  '2024-25',
  12.0,
  6.5,
  4.8,
  40.00,   -- 4.8/12.0*100
  7.2,     -- 12.0 - 4.8
  58.0,
  'early_implementation',
  'high',
  true,
  false,
  false,
  ARRAY['slow_disbursement','security_access','capacity_gap'],
  true,
  'World Bank/FCDO',
  'ta_opportunity',
  80.0,
  60.0,
  'World Bank and FCDO requiring institutional capacity TA for newly merged tribal districts.',
  'Capacity building TA for tribal district administration — explicitly scoped. High strategic value.',
  'Merged district administrations lack planning and financial management capacity.',
  'World Bank/FCDO-funded tribal district capacity building TA.',
  3,
  1
),

(
  'ADP-KP-007',
  'Malakand Water Supply Scheme',
  'PHE KP',
  'Public Health Engineering KP',
  'KP',
  'Malakand',
  'Water/Sanitation',
  'Rural Water Supply',
  'provincial_adp',
  '2024-25',
  3.5,
  1.8,
  1.05,
  30.00,   -- 1.05/3.5*100
  2.45,    -- 3.5 - 1.05
  17.0,
  'early_implementation',
  'high',
  true,
  false,
  false,
  ARRAY['slow_disbursement','contractor_capacity'],
  false,
  NULL,
  'supervision',
  72.0,
  70.0,
  NULL,
  'Water supply supervision and O&M advisory; PHE KP procurement accessible.',
  'Pump station civil works stalled; contractor equipment breakdown.',
  'Construction supervision and O&M advisory.',
  2,
  1
),

(
  'ADP-KP-008',
  'KP Agriculture Transformation Plan',
  'Agriculture KP',
  'Agriculture Department KP',
  'KP',
  'Multiple',
  'Agriculture',
  'Agri-Value Chain',
  'provincial_adp',
  '2024-25',
  6.0,
  3.5,
  2.4,
  40.00,   -- 2.4/6.0*100
  3.6,     -- 6.0 - 2.4
  30.0,
  'early_implementation',
  'medium',
  false,
  false,
  false,
  ARRAY['procurement_delay'],
  true,
  'IFAD',
  'none',
  60.0,
  60.0,
  'IFAD tracking value chain development; satisfactory.',
  'Value chain and agri-market advisory; IFAD channel.',
  'Horticultural value chain development in Swat and Hazara divisions progressing.',
  'IFAD-funded agri-market advisory niche.',
  3,
  0
),

(
  'ADP-KP-009',
  'Hazara Motorway Land Acquisition',
  'C&W KP',
  'Communication & Works KP',
  'KP',
  'Abbottabad',
  'Transport',
  'Motorway',
  'provincial_adp',
  '2024-25',
  5.0,
  1.5,
  1.0,
  20.00,   -- 1.0/5.0*100
  4.0,     -- 5.0 - 1.0
  24.0,
  'mobilization',
  'critical',
  true,
  true,
  true,
  ARRAY['land_acquisition','legal_dispute','slow_disbursement','extension_risk'],
  false,
  NULL,
  'supervision',
  85.0,
  88.0,
  NULL,
  'Land acquisition advisory and legal support niche; C&W KP facing court challenges.',
  'Hundreds of landowners contesting acquisition price; court injunctions halting 30 km of alignment.',
  'Land acquisition legal advisory and resettlement planning support.',
  4,
  2
),

(
  'ADP-KP-010',
  'KP District Health Systems Strengthening',
  'Health KP',
  'Health Department KP / WHO',
  'KP',
  'Multiple',
  'Health',
  'Health Systems',
  'provincial_adp',
  '2024-25',
  4.5,
  2.5,
  1.8,
  40.00,   -- 1.8/4.5*100
  2.7,     -- 4.5 - 1.8
  22.0,
  'early_implementation',
  'high',
  true,
  false,
  false,
  ARRAY['slow_disbursement','pmu_weakness'],
  true,
  'USAID/WHO',
  'monitoring_evaluation',
  72.0,
  60.0,
  'USAID and WHO requiring independent health systems assessment.',
  'Health systems M&E advisory via USAID or WHO Pakistan procurement.',
  'DHIS2 data quality weak in southern KP districts; district health officer vacancies.',
  'USAID/WHO-funded health systems assessment and advisory.',
  2,
  0
),

-- ============================================================
-- PROVINCIAL ADP — BALOCHISTAN (10 schemes)
-- ============================================================

(
  'ADP-BLN-001',
  'Balochistan Urban Policy and Management',
  'LG&RD Balochistan',
  'Balochistan Urban Policy Unit',
  'Balochistan',
  'Quetta',
  'Governance',
  'Urban Management',
  'provincial_adp',
  '2024-25',
  3.0,
  1.5,
  0.9,
  30.00,   -- 0.9/3.0*100
  2.1,     -- 3.0 - 0.9
  14.0,
  'early_implementation',
  'critical',
  true,
  false,
  false,
  ARRAY['slow_disbursement','capacity_gap','institutional_fragmentation'],
  false,
  NULL,
  'ta_opportunity',
  85.0,
  70.0,
  NULL,
  'Urban policy and municipal finance TA — high-value niche in Balochistan.',
  'Urban policy unit has 2 professional staff; municipal finance reform stalled.',
  'Urban policy TA and municipal finance capacity building advisory.',
  2,
  1
),

(
  'ADP-BLN-002',
  'Quetta Water Supply Augmentation',
  'PHE Balochistan',
  'Quetta Development Authority',
  'Balochistan',
  'Quetta',
  'Water/Sanitation',
  'Urban Water Supply',
  'provincial_adp',
  '2024-25',
  8.0,
  3.5,
  2.4,
  30.00,   -- 2.4/8.0*100
  5.6,     -- 8.0 - 2.4
  40.0,
  'early_implementation',
  'critical',
  true,
  true,
  true,
  ARRAY['slow_disbursement','land_acquisition','security_access','cost_overrun','extension_risk'],
  true,
  'ADB/KfW',
  'supervision',
  92.0,
  88.0,
  'ADB and KfW both expressing serious concern; water scarcity crisis in Quetta worsening.',
  'Supervision and PMO advisory — critical. ADB and KfW both have open procurement.',
  'Aquifer depletion accelerating; new source (Kuchlak) pipeline facing land and security issues.',
  'ADB/KfW-funded supervision and PMO support — urgently needed.',
  5,
  3
),

(
  'ADP-BLN-003',
  'Balochistan Education Support Programme',
  'Education Balochistan',
  'Balochistan Education Foundation',
  'Balochistan',
  'Multiple',
  'Education',
  'Basic Education',
  'provincial_adp',
  '2024-25',
  6.0,
  2.5,
  1.8,
  30.00,   -- 1.8/6.0*100
  4.2,     -- 6.0 - 1.8
  30.0,
  'early_implementation',
  'critical',
  true,
  false,
  false,
  ARRAY['slow_disbursement','capacity_gap','girls_enrolment_gap'],
  true,
  'FCDO/EU',
  'ta_opportunity',
  90.0,
  70.0,
  'FCDO and EU explicitly requiring education system TA; girls'' enrolment critically low.',
  'Education TA — one of highest-value consulting opportunities in Balochistan. Track FCDO and EU tenders.',
  'Balochistan has the lowest female school enrolment in Pakistan; structural barriers deep.',
  'FCDO/EU-funded girls'' education TA and system reform advisory.',
  4,
  1
),

(
  'ADP-BLN-004',
  'Turbat-Hoshab Road Connectivity',
  'C&W Balochistan',
  'Communication & Works Balochistan',
  'Balochistan',
  'Kech',
  'Transport',
  'National Highway',
  'provincial_adp',
  '2024-25',
  5.5,
  2.5,
  1.65,
  30.00,   -- 1.65/5.5*100
  3.85,    -- 5.5 - 1.65
  28.0,
  'early_implementation',
  'critical',
  true,
  false,
  false,
  ARRAY['security_access','contractor_capacity','slow_disbursement'],
  false,
  NULL,
  'supervision',
  88.0,
  70.0,
  NULL,
  'Supervision advisory; security clearance required for field access.',
  'Active security operations in Kech district causing repeated contractor evacuation.',
  'Supervision advisory with remote-monitoring capability given security constraints.',
  4,
  1
),

(
  'ADP-BLN-005',
  'Balochistan Integrated Health Programme',
  'Health Balochistan',
  'Health Department Balochistan',
  'Balochistan',
  'Multiple',
  'Health',
  'Primary Healthcare',
  'provincial_adp',
  '2024-25',
  4.5,
  1.5,
  0.9,
  20.00,   -- 0.9/4.5*100
  3.6,     -- 4.5 - 0.9
  22.0,
  'mobilization',
  'critical',
  true,
  false,
  false,
  ARRAY['capacity_gap','supply_chain_failure','security_access'],
  true,
  'WHO/UNICEF',
  'ta_opportunity',
  92.0,
  88.0,
  'WHO and UNICEF both requiring integrated health TA; under-5 mortality in Balochistan is a global outlier.',
  'Health system TA — highest-priority opportunity in Pakistan for health sector consultants.',
  'Health facilities in Balochistan among the most under-resourced globally; staff vacancy rate 65%.',
  'WHO/UNICEF-funded health system TA and supply chain advisory — imminently.',
  3,
  2
),

(
  'ADP-BLN-006',
  'Mirani Dam Irrigation Network',
  'Irrigation Balochistan',
  'Balochistan Irrigation and Power Dept',
  'Balochistan',
  'Turbat',
  'Agriculture',
  'Irrigation',
  'provincial_adp',
  '2024-25',
  7.0,
  3.0,
  2.1,
  30.00,   -- 2.1/7.0*100
  4.9,     -- 7.0 - 2.1
  34.0,
  'early_implementation',
  'high',
  true,
  false,
  false,
  ARRAY['slow_disbursement','security_access','contractor_default'],
  false,
  NULL,
  'supervision',
  78.0,
  70.0,
  NULL,
  'Irrigation network supervision advisory; BIPD procurement accessible.',
  'Canal lining contractor defaulted; re-tendering expected Q2 FY2025.',
  'Re-tendering and construction supervision advisory following contractor default.',
  5,
  2
),

(
  'ADP-BLN-007',
  'Gwadar Development Authority Infrastructure',
  'Planning Balochistan',
  'Gwadar Development Authority',
  'Balochistan',
  'Gwadar',
  'Transport',
  'Port City Infrastructure',
  'provincial_adp',
  '2024-25',
  12.0,
  6.5,
  4.8,
  40.00,   -- 4.8/12.0*100
  7.2,     -- 12.0 - 4.8
  58.0,
  'early_implementation',
  'medium',
  false,
  false,
  true,
  ARRAY['land_acquisition'],
  true,
  'China/CPEC',
  'none',
  55.0,
  60.0,
  'China CPEC financing; tied procurement. GDA managing directly.',
  'Limited non-Chinese consulting entry; urban planning advisory possible if untied component found.',
  'Gwadar port city master plan implementation; Chinese contractors dominant.',
  'Urban planning advisory for non-CPEC components.',
  6,
  1
),

(
  'ADP-BLN-008',
  'Balochistan Livestock and Dairy Development',
  'Agriculture Balochistan',
  'Livestock and Dairy Development Department',
  'Balochistan',
  'Multiple',
  'Agriculture',
  'Livestock',
  'provincial_adp',
  '2024-25',
  3.0,
  1.2,
  0.9,
  30.00,   -- 0.9/3.0*100
  2.1,     -- 3.0 - 0.9
  14.0,
  'early_implementation',
  'high',
  true,
  false,
  false,
  ARRAY['slow_disbursement','capacity_gap'],
  false,
  NULL,
  'supervision',
  70.0,
  70.0,
  NULL,
  'Livestock value chain and veterinary advisory; LDDD Balochistan accessible.',
  'Vaccine cold chain and artificial insemination programme behind target.',
  'Livestock value chain and veterinary services advisory.',
  2,
  1
),

(
  'ADP-BLN-009',
  'Chaman Border Crossing Infrastructure',
  'C&W Balochistan',
  'Chaman Customs and NLC',
  'Balochistan',
  'Chaman',
  'Transport',
  'Border Infrastructure',
  'provincial_adp',
  '2024-25',
  4.0,
  2.0,
  1.2,
  30.00,   -- 1.2/4.0*100
  2.8,     -- 4.0 - 1.2
  20.0,
  'early_implementation',
  'high',
  true,
  false,
  false,
  ARRAY['slow_disbursement','security_access','border_closure_risk'],
  false,
  NULL,
  'supervision',
  65.0,
  70.0,
  NULL,
  'Border management and trade facilitation advisory.',
  'Pakistan-Afghanistan border closures periodically halting construction access.',
  'Border management and trade facilitation advisory.',
  2,
  1
),

(
  'ADP-BLN-010',
  'Balochistan Solar Electrification Off-Grid',
  'Energy Balochistan',
  'Balochistan Energy Department',
  'Balochistan',
  'Multiple',
  'Energy',
  'Off-Grid Solar',
  'provincial_adp',
  '2024-25',
  5.0,
  3.8,
  2.5,
  50.00,   -- 2.5/5.0*100
  2.5,     -- 5.0 - 2.5
  24.0,
  'mid_implementation',
  'medium',
  false,
  false,
  false,
  ARRAY[]::text[],
  true,
  'IsDB/OPEC Fund',
  'none',
  65.0,
  50.0,
  'IsDB and OPEC Fund satisfied with solar installation pace.',
  'Limited new consulting entry; O&M and community management advisory possible.',
  'Off-grid solar installation for 800 villages progressing well in accessible areas.',
  'O&M and community energy management advisory.',
  3,
  0
)

ON CONFLICT (scheme_id) DO UPDATE SET
  title                  = EXCLUDED.title,
  ministry               = EXCLUDED.ministry,
  executing_agency       = EXCLUDED.executing_agency,
  province               = EXCLUDED.province,
  district               = EXCLUDED.district,
  sector                 = EXCLUDED.sector,
  sub_sector             = EXCLUDED.sub_sector,
  source                 = EXCLUDED.source,
  fiscal_year            = EXCLUDED.fiscal_year,
  allocation_bn          = EXCLUDED.allocation_bn,
  released_bn            = EXCLUDED.released_bn,
  utilized_bn            = EXCLUDED.utilized_bn,
  execution_pct          = EXCLUDED.execution_pct,
  throwforward_bn        = EXCLUDED.throwforward_bn,
  total_approved_cost_bn = EXCLUDED.total_approved_cost_bn,
  implementation_stage   = EXCLUDED.implementation_stage,
  risk_level             = EXCLUDED.risk_level,
  is_slow_moving         = EXCLUDED.is_slow_moving,
  is_time_overrun        = EXCLUDED.is_time_overrun,
  is_revised             = EXCLUDED.is_revised,
  warning_signals        = EXCLUDED.warning_signals,
  is_donor_linked        = EXCLUDED.is_donor_linked,
  donor_name             = EXCLUDED.donor_name,
  opportunity_type       = EXCLUDED.opportunity_type,
  opportunity_score      = EXCLUDED.opportunity_score,
  execution_stress_score = EXCLUDED.execution_stress_score,
  donor_perspective      = EXCLUDED.donor_perspective,
  firm_perspective       = EXCLUDED.firm_perspective,
  implementer_perspective= EXCLUDED.implementer_perspective,
  opportunity_window     = EXCLUDED.opportunity_window,
  years_in_portfolio     = EXCLUDED.years_in_portfolio,
  pc1_revision_count     = EXCLUDED.pc1_revision_count,
  updated_at             = now();

-- ================================================================
-- Views should already exist from migration 0009. Run the following
-- only if views are missing:
-- ================================================================

CREATE OR REPLACE VIEW public.psdp_province_summary AS
SELECT
  COALESCE(province, 'Federal')                                   AS province,
  COUNT(*)                                                        AS scheme_count,
  ROUND(SUM(COALESCE(allocation_bn, 0))::numeric, 2)             AS total_allocation_bn,
  ROUND(SUM(COALESCE(utilized_bn,   0))::numeric, 2)             AS total_utilized_bn,
  ROUND(AVG(COALESCE(execution_pct, 0))::numeric, 1)             AS avg_execution_pct,
  ROUND(SUM(COALESCE(throwforward_bn, 0))::numeric, 2)           AS total_throwforward_bn,
  COUNT(*) FILTER (WHERE is_slow_moving)                          AS slow_moving_count,
  COUNT(*) FILTER (WHERE risk_level IN ('high', 'critical'))      AS high_risk_count,
  COUNT(*) FILTER (WHERE is_donor_linked)                         AS donor_linked_count,
  ROUND(AVG(COALESCE(opportunity_score,      0))::numeric, 1)    AS avg_opportunity_score,
  ROUND(AVG(COALESCE(execution_stress_score, 0))::numeric, 1)    AS avg_stress_score
FROM public.psdp_schemes
GROUP BY COALESCE(province, 'Federal')
ORDER BY total_allocation_bn DESC;

-- ----------------------------------------------------------------

CREATE OR REPLACE VIEW public.psdp_ministry_efficiency AS
SELECT
  COALESCE(ministry, 'Unknown')                                   AS ministry,
  COUNT(*)                                                        AS scheme_count,
  ROUND(SUM(COALESCE(allocation_bn,    0))::numeric, 2)          AS total_allocation_bn,
  ROUND(SUM(COALESCE(utilized_bn,      0))::numeric, 2)          AS total_utilized_bn,
  ROUND(AVG(COALESCE(execution_pct,    0))::numeric, 1)          AS avg_execution_pct,
  ROUND(SUM(COALESCE(throwforward_bn,  0))::numeric, 2)          AS total_throwforward_bn,
  COUNT(*) FILTER (WHERE is_slow_moving)                          AS slow_moving_count,
  ROUND(AVG(COALESCE(opportunity_score, 0))::numeric, 1)         AS avg_opportunity_score,
  ROUND(
    CASE WHEN SUM(COALESCE(allocation_bn, 0)) > 0
         THEN SUM(COALESCE(throwforward_bn, 0))
              / SUM(COALESCE(allocation_bn, 0)) * 100
         ELSE 0
    END::numeric, 1
  )                                                               AS backlog_pct
FROM public.psdp_schemes
GROUP BY COALESCE(ministry, 'Unknown')
ORDER BY total_allocation_bn DESC;

-- ----------------------------------------------------------------

CREATE OR REPLACE VIEW public.psdp_sector_intelligence AS
SELECT
  COALESCE(sector, 'Uncategorised')                              AS sector,
  COUNT(*)                                                       AS scheme_count,
  ROUND(SUM(COALESCE(allocation_bn,   0))::numeric, 2)          AS total_allocation_bn,
  ROUND(SUM(COALESCE(utilized_bn,     0))::numeric, 2)          AS total_utilized_bn,
  ROUND(AVG(COALESCE(execution_pct,   0))::numeric, 1)          AS avg_execution_pct,
  ROUND(SUM(COALESCE(throwforward_bn, 0))::numeric, 2)          AS total_throwforward_bn,
  COUNT(*) FILTER (WHERE opportunity_type != 'none')             AS schemes_with_opportunities,
  ROUND(AVG(COALESCE(opportunity_score,      0))::numeric, 1)   AS avg_opportunity_score,
  ROUND(AVG(COALESCE(execution_stress_score, 0))::numeric, 1)   AS avg_stress_score,
  COUNT(*) FILTER (WHERE is_donor_linked)                        AS donor_linked_count
FROM public.psdp_schemes
GROUP BY COALESCE(sector, 'Uncategorised')
ORDER BY total_allocation_bn DESC;

-- ----------------------------------------------------------------
-- Grant SELECT on views to authenticated users (idempotent)
-- ----------------------------------------------------------------
GRANT SELECT ON public.psdp_province_summary    TO authenticated;
GRANT SELECT ON public.psdp_ministry_efficiency  TO authenticated;
GRANT SELECT ON public.psdp_sector_intelligence  TO authenticated;
